#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import json

# 汉字数据
characters = [
    {"char": "日", "pinyin": "rì", "english": "Sun", "category": "自然", "emoji": "☀️", "radical": "日", "strokes": 4, "stroke_order": ["竖", "横折", "横", "横"], "origin": {"oracle": "⊙", "seal": "日", "meaning": "古人画一个圆圈加点表示太阳"}, "story_cn": "太阳公公每天早早起床，照亮大地。圆圆的太阳像大火球，带来温暖和光明。", "story_en": "Grandpa Sun wakes early each day, lighting up the earth. The round sun is like a big fireball bringing warmth and light.", "words": ["日出 rì chū · Sunrise", "生日 shēng rì · Birthday", "日记 rì jì · Diary", "阳光 yáng guāng · Sunshine"]},
    {"char": "月", "pinyin": "yuè", "english": "Moon", "category": "自然", "emoji": "🌙", "radical": "月", "strokes": 4, "stroke_order": ["撇", "横折钩", "横", "横"], "origin": {"oracle": "☽", "seal": "月", "meaning": "古人画弯弯的形状表示月亮"}, "story_cn": "夜晚，弯弯的月亮挂在天空像一艘小船，小星星们围着月亮姐姐眨眼睛。", "story_en": "At night the crescent moon hangs like a small boat. Little stars twinkle around Sister Moon.", "words": ["月亮 yuè liàng · Moon", "月饼 yuè bǐng · Mooncake", "一月 yī yuè · January", "岁月 suì yuè · Years"]},
    {"char": "山", "pinyin": "shān", "english": "Mountain", "category": "自然", "emoji": "⛰️", "radical": "山", "strokes": 3, "stroke_order": ["竖", "竖折", "竖"], "origin": {"oracle": "⛰", "seal": "山", "meaning": "古人画三个山峰表示山"}, "story_cn": "高高的山峰直插云霄，小松鼠住在山上，每天在树林里跳来跳去。", "story_en": "Tall peaks reach into the clouds. A little squirrel lives on the mountain, jumping among trees.", "words": ["火山 huǒ shān · Volcano", "爬山 pá shān · Climbing", "山水 shān shuǐ · Landscape", "高山 gāo shān · High mountain"]},
    {"char": "水", "pinyin": "shuǐ", "english": "Water", "category": "自然", "emoji": "💧", "radical": "水", "strokes": 4, "stroke_order": ["竖钩", "横撇", "撇", "捺"], "origin": {"oracle": "〰", "seal": "水", "meaning": "古人画流动的波浪表示水"}, "story_cn": "哗啦啦小溪在唱歌，水滴从高处落下溅起美丽水花，小鱼在水里游来游去。", "story_en": "Splash splash the stream sings, water drops fall high making splashes, little fish swims happily.", "words": ["水果 shuǐ guǒ · Fruit", "喝水 hē shuǐ · Drink water", "河水 hé shuǐ · River water", "雨水 yǔ shuǐ · Rainwater"]},
    {"char": "火", "pinyin": "huǒ", "english": "Fire", "category": "自然", "emoji": "🔥", "radical": "火", "strokes": 4, "stroke_order": ["点", "撇", "撇", "捺"], "origin": {"oracle": "🔥", "seal": "火", "meaning": "古人画火焰形状表示火"}, "story_cn": "篝火晚会开始了！火焰跳动像在跳舞。火可以做饭取暖，但小朋友不能玩火！", "story_en": "Campfire party begins! Flames dance. Fire cooks and keeps warm, but kids must never play with fire!", "words": ["火车 huǒ chē · Train", "烟火 yān huǒ · Fireworks", "大火 dà huǒ · Big fire", "灭火 miè huǒ · Extinguish fire"]},
    {"char": "天", "pinyin": "tiān", "english": "Sky/Day", "category": "自然", "emoji": "🌤️", "radical": "大", "strokes": 4, "stroke_order": ["横", "横", "撇", "捺"], "origin": {"oracle": "☁", "seal": "天", "meaning": "古人画一个人头顶上的空间表示天"}, "story_cn": "蓝蓝的天空飘着白云，小鸟在天空中自由飞翔。天空真大真美啊！", "story_en": "White clouds float in blue sky, birds fly freely. The sky is so big and beautiful!", "words": ["天空 tiān kōng · Sky", "今天 jīn tiān · Today", "天气 tiān qì · Weather", "天天 tiān tiān · Every day"]},
    {"char": "云", "pinyin": "yún", "english": "Cloud", "category": "自然", "emoji": "☁️", "radical": "二", "strokes": 4, "stroke_order": ["横", "横", "撇折", "点"], "origin": {"oracle": "☁", "seal": "云", "meaning": "古人画云朵形状表示云"}, "story_cn": "白云像棉花糖飘在天上。乌云来了就要下雨，云朵变化无穷真有趣！", "story_en": "White clouds float like cotton candy. When dark clouds come rain follows. Clouds change endlessly!", "words": ["白云 bái yún · White cloud", "云彩 yún cǎi · Clouds", "乌云 wū yún · Dark cloud", "云朵 yún duǒ · Cloud"]},
    {"char": "雨", "pinyin": "yǔ", "english": "Rain", "category": "自然", "emoji": "🌧️", "radical": "雨", "strokes": 8, "stroke_order": ["横", "竖", "横折钩", "竖", "点", "点", "点", "点"], "origin": {"oracle": "🌧", "seal": "雨", "meaning": "古人画水滴从天上落下表示雨"}, "story_cn": "小雨滴滴答答落下来，花儿喝足了水开得更鲜艳。下雨天可以踩水洼，好开心！", "story_en": "Light rain falls patter-patter. Flowers drink enough water and bloom brighter. Splashing puddles is fun!", "words": ["下雨 xià yǔ · Rain", "雨伞 yǔ sǎn · Umbrella", "雨水 yǔ shuǐ · Rainwater", "雨衣 yǔ yī · Raincoat"]},
    {"char": "风", "pinyin": "fēng", "english": "Wind", "category": "自然", "emoji": "🌬️", "radical": "风", "strokes": 4, "stroke_order": ["撇", "横折弯钩", "撇", "点"], "origin": {"oracle": "🌀", "seal": "风", "meaning": "古人画风吹动的形状表示风"}, "story_cn": "呼呼呼，风儿吹过树叶沙沙响。春风温暖，秋风凉爽，风真神奇！", "story_en": "Whoo whoo, wind blows through trees making rustling sounds. Spring wind is warm, autumn wind is cool!", "words": ["大风 dà fēng · Big wind", "风吹 fēng chuī · Wind blows", "风车 fēng chē · Windmill", "春风 chūn fēng · Spring wind"]},
    {"char": "雪", "pinyin": "xuě", "english": "Snow", "category": "自然", "emoji": "❄️", "radical": "雨", "strokes": 11, "stroke_order": ["横", "竖", "横折钩", "竖", "点", "点", "点", "点", "横", "横", "横"], "origin": {"oracle": "❄", "seal": "雪", "meaning": "古人画雨变成白色颗粒表示雪"}, "story_cn": "冬天来了，白雪飘下来，大地盖上白色棉被。小朋友堆雪人打雪仗，好开心！", "story_en": "Winter arrives, snowflakes fall, earth covers with white quilt. Kids build snowmen and snowball fights!", "words": ["下雪 xià xuě · Snowing", "雪花 xuě huā · Snowflake", "雪人 xuě rén · Snowman", "白雪 bái xuě · White snow"]},
    {"char": "花", "pinyin": "huā", "english": "Flower", "category": "植物", "emoji": "🌸", "radical": "艹", "strokes": 7, "stroke_order": ["横", "竖", "竖", "撇", "竖弯钩", "撇", "竖弯钩"], "origin": {"oracle": "🌸", "seal": "花", "meaning": "古人画花草形状表示花"}, "story_cn": "春天来了，花儿开了！红的、黄的、紫的，五颜六色的花儿真美丽！", "story_en": "Spring comes, flowers bloom! Red, yellow, purple - colorful flowers are so beautiful!", "words": ["花朵 huā duǒ · Flower", "鲜花 xiān huā · Fresh flower", "花园 huā yuán · Garden", "开花 kāi huā · Bloom"]},
    {"char": "草", "pinyin": "cǎo", "english": "Grass", "category": "植物", "emoji": "🌿", "radical": "艹", "strokes": 9, "stroke_order": ["横", "竖", "竖", "竖", "横折", "横", "横", "竖", "撇"], "origin": {"oracle": "🌿", "seal": "草", "meaning": "古人画小草形状表示草"}, "story_cn": "绿绿的小草长在地上，小羊喜欢吃草。草地上可以踢球玩耍！", "story_en": "Green grass grows on the ground, little sheep like to eat grass. We can play ball on the grass!", "words": ["草地 cǎo dì · Grassland", "小草 xiǎo cǎo · Little grass", "青草 qīng cǎo · Green grass", "草坪 cǎo píng · Lawn"]},
    {"char": "树", "pinyin": "shù", "english": "Tree", "category": "植物", "emoji": "🌳", "radical": "木", "strokes": 9, "stroke_order": ["横", "竖", "撇", "点", "横", "竖", "撇", "捺", "点"], "origin": {"oracle": "🌳", "seal": "树", "meaning": "古人画树木形状表示树"}, "story_cn": "大树高高，树叶茂密。小鸟在树上筑巢，小朋友在树下乘凉。", "story_en": "Big trees are tall with dense leaves. Birds build nests in trees, children rest under them.", "words": ["大树 dà shù · Big tree", "树木 shù mù · Trees", "树林 shù lín · Forest", "树叶 shù yè · Leaf"]},
    {"char": "木", "pinyin": "mù", "english": "Wood", "category": "植物", "emoji": "🪵", "radical": "木", "strokes": 4, "stroke_order": ["横", "竖", "撇", "捺"], "origin": {"oracle": "🪵", "seal": "木", "meaning": "古人画树干和树枝表示木"}, "story_cn": "木头可以做成桌椅、房子。木是树的一部分，很有用！", "story_en": "Wood can be made into tables, chairs, and houses. Wood is part of trees, very useful!", "words": ["木头 mù tou · Wood", "木材 mù cái · Timber", "木椅 mù yǐ · Wooden chair", "木门 mù mén · Wooden door"]},
    {"char": "林", "pinyin": "lín", "english": "Forest", "category": "植物", "emoji": "🌲", "radical": "木", "strokes": 8, "stroke_order": ["横", "竖", "撇", "捺", "横", "竖", "撇", "捺"], "origin": {"oracle": "🌲", "seal": "林", "meaning": "两个木在一起表示很多树"}, "story_cn": "森林里有很多树，小动物们住在里面。树林里空气清新，真舒服！", "story_en": "The forest has many trees, little animals live inside. The air in the forest is fresh and comfortable!", "words": ["森林 sēn lín · Forest", "树林 shù lín · Woods", "林间 lín jiān · Among trees", "林子 lín zi · Woods"]},
    {"char": "叶", "pinyin": "yè", "english": "Leaf", "category": "植物", "emoji": "🍃", "radical": "口", "strokes": 5, "stroke_order": ["竖", "横折", "横", "横", "竖"], "origin": {"oracle": "🍃", "seal": "叶", "meaning": "古人画树枝上的叶片表示叶"}, "story_cn": "树叶绿绿的，秋天变黄飘落。叶子可以给小虫子当家。", "story_en": "Leaves are green, turning yellow and falling in autumn. Leaves can be homes for little bugs.", "words": ["树叶 shù yè · Tree leaf", "叶子 yè zi · Leaf", "绿叶 lǜ yè · Green leaf", "落叶 luò yè · Fallen leaf"]},
    {"char": "果", "pinyin": "guǒ", "english": "Fruit", "category": "植物", "emoji": "🍎", "radical": "木", "strokes": 8, "stroke_order": ["竖", "横折", "横", "横", "横", "竖", "撇", "捺"], "origin": {"oracle": "🍎", "seal": "果", "meaning": "古人画树上的果实表示果"}, "story_cn": "苹果、香蕉、橘子都是水果。水果甜甜的，小朋友都爱吃！", "story_en": "Apples, bananas, oranges are all fruits. Fruits are sweet, children love to eat them!", "words": ["水果 shuǐ guǒ · Fruit", "苹果 píng guǒ · Apple", "果实 guǒ shí · Fruit", "果树 guǒ shù · Fruit tree"]},
    {"char": "鸟", "pinyin": "niǎo", "english": "Bird", "category": "动物", "emoji": "🐦", "radical": "鸟", "strokes": 5, "stroke_order": ["撇", "横折钩", "点", "竖折折钩", "横"], "origin": {"oracle": "🐦", "seal": "鸟", "meaning": "古人画鸟的形状表示鸟"}, "story_cn": "小鸟在天空中飞翔，唱着美妙的歌。鸟妈妈照顾小鸟宝宝，真温馨！", "story_en": "Little birds fly in the sky, singing beautiful songs. Bird mom takes care of baby birds, so warm!", "words": ["小鸟 xiǎo niǎo · Little bird", "鸟儿 niǎo ér · Bird", "鸟巢 niǎo cháo · Nest", "飞鸟 fēi niǎo · Flying bird"]},
    {"char": "鱼", "pinyin": "yú", "english": "Fish", "category": "动物", "emoji": "🐟", "radical": "鱼", "strokes": 8, "stroke_order": ["撇", "横撇", "竖", "横折", "横", "竖", "横", "横"], "origin": {"oracle": "🐟", "seal": "鱼", "meaning": "古人画鱼的形状表示鱼"}, "story_cn": "小鱼在水里游来游去，鱼鳞闪闪发光。钓鱼是很有趣的活动！", "story_en": "Little fish swim in water, scales shining. Fishing is a fun activity!", "words": ["小鱼 xiǎo yú · Little fish", "鱼儿 yú ér · Fish", "钓鱼 diào yú · Fishing", "金鱼 jīn yú · Goldfish"]},
    {"char": "马", "pinyin": "mǎ", "english": "Horse", "category": "动物", "emoji": "🐴", "radical": "马", "strokes": 3, "stroke_order": ["横折", "竖折折钩", "横"], "origin": {"oracle": "🐴", "seal": "马", "meaning": "古人画马的形状表示马"}, "story_cn": "马儿跑得很快，可以帮人运输东西。骑马是一项有趣的运动！", "story_en": "Horses run fast, helping people transport things. Horse riding is a fun sport!", "words": ["小马 xiǎo mǎ · Little horse", "骑马 qí mǎ · Ride horse", "马车 mǎ chē · Horse cart", "马儿 mǎ ér · Horse"]},
    {"char": "牛", "pinyin": "niú", "english": "Cow", "category": "动物", "emoji": "🐄", "radical": "牛", "strokes": 4, "stroke_order": ["撇", "横", "横", "竖"], "origin": {"oracle": "🐄", "seal": "牛", "meaning": "古人画牛头形状表示牛"}, "story_cn": "牛是勤劳的动物，可以帮农民耕田。牛奶很有营养！", "story_en": "Cows are hardworking animals, helping farmers plow fields. Milk is very nutritious!", "words": ["小牛 xiǎo niú · Little cow", "牛奶 niú nǎi · Milk", "黄牛 huáng niú · Yellow cow", "牛儿 niú ér · Cow"]},
    {"char": "羊", "pinyin": "yáng", "english": "Sheep", "category": "动物", "emoji": "🐑", "radical": "羊", "strokes": 6, "stroke_order": ["撇", "横", "横", "横", "竖", "竖"], "origin": {"oracle": "🐑", "seal": "羊", "meaning": "古人画羊头形状表示羊"}, "story_cn": "小羊喜欢吃草，羊毛可以做衣服。羊儿温顺可爱！", "story_en": "Little sheep like eating grass, wool can make clothes. Sheep are gentle and cute!", "words": ["小羊 xiǎo yáng · Little sheep", "山羊 shān yáng · Goat", "羊毛 yáng máo · Wool", "羊儿 yáng ér · Sheep"]},
    {"char": "狗", "pinyin": "gǒu", "english": "Dog", "category": "动物", "emoji": "🐕", "radical": "犭", "strokes": 8, "stroke_order": ["撇", "横弯钩", "撇", "横", "竖", "横折", "横", "横"], "origin": {"oracle": "🐕", "seal": "狗", "meaning": "古人画狗的形状表示狗"}, "story_cn": "小狗是人类的好朋友，会看家、会玩耍。狗狗忠诚可爱！", "story_en": "Dogs are human's good friends, guarding homes and playing. Dogs are loyal and cute!", "words": ["小狗 xiǎo gǒu · Little dog", "狗狗 gǒu gǒu · Doggy", "宠物狗 chǒng wù gǒu · Pet dog", "狗儿 gǒu ér · Dog"]},
    {"char": "猫", "pinyin": "māo", "english": "Cat", "category": "动物", "emoji": "🐱", "radical": "犭", "strokes": 11, "stroke_order": ["撇", "横弯钩", "撇", "横", "竖", "竖", "横折", "横", "竖", "横", "横"], "origin": {"oracle": "🐱", "seal": "猫", "meaning": "古人画猫的形状表示猫"}, "story_cn": "小猫咪喵喵叫，喜欢抓老鼠。猫咪软软的，抱起来很舒服！", "story_en": "Little cats meow, like catching mice. Cats are soft, holding them is comfortable!", "words": ["小猫 xiǎo māo · Little cat", "猫咪 māo mī · Kitty", "宠物猫 chǒng wù māo · Pet cat", "猫儿 māo ér · Cat"]},
    {"char": "虫", "pinyin": "chóng", "english": "Insect", "category": "动物", "emoji": "🐛", "radical": "虫", "strokes": 6, "stroke_order": ["竖", "横折", "横", "竖", "横", "点"], "origin": {"oracle": "🐛", "seal": "虫", "meaning": "古人画虫子形状表示虫"}, "story_cn": "小虫子在草丛里爬，蝴蝶是美丽的虫子。虫子世界很奇妙！", "story_en": "Little bugs crawl in grass, butterflies are beautiful insects. The insect world is amazing!", "words": ["小虫 xiǎo chóng · Little bug", "昆虫 kūn chóng · Insect", "虫子 chóng zi · Bug", "蝴蝶 hú dié · Butterfly"]},
    {"char": "人", "pinyin": "rén", "english": "Person", "category": "身体", "emoji": "🧍", "radical": "人", "strokes": 2, "stroke_order": ["撇", "捺"], "origin": {"oracle": "🧍", "seal": "人", "meaning": "古人画站立的人形表示人"}, "story_cn": "人是世界上最聪明的动物，会说话、会思考、会创造。", "story_en": "Humans are the smartest animals, can speak, think, and create.", "words": ["人们 rén men · People", "人类 rén lèi · Human", "好人 hǎo rén · Good person", "大人 dà rén · Adult"]},
    {"char": "手", "pinyin": "shǒu", "english": "Hand", "category": "身体", "emoji": "✋", "radical": "手", "strokes": 4, "stroke_order": ["撇", "横", "横", "竖钩"], "origin": {"oracle": "✋", "seal": "手", "meaning": "古人画手掌形状表示手"}, "story_cn": "手可以做很多事情：写字、画画、吃饭、玩耍。保护小手很重要！", "story_en": "Hands can do many things: write, draw, eat, play. Protecting little hands is important!", "words": ["小手 xiǎo shǒu · Little hand", "双手 shuāng shǒu · Two hands", "手指 shǒu zhǐ · Finger", "握手 wò shǒu · Shake hands"]},
    {"char": "口", "pinyin": "kǒu", "english": "Mouth", "category": "身体", "emoji": "👄", "radical": "口", "strokes": 3, "stroke_order": ["竖", "横折", "横"], "origin": {"oracle": "👄", "seal": "口", "meaning": "古人画嘴巴形状表示口"}, "story_cn": "嘴巴可以吃饭、说话、唱歌。微笑是最美的表情！", "story_en": "Mouth can eat, speak, sing. Smile is the most beautiful expression!", "words": ["嘴巴 zuǐ ba · Mouth", "开口 kāi kǒu · Open mouth", "人口 rén kǒu · Population", "口水 kǒu shuǐ · Saliva"]},
    {"char": "目", "pinyin": "mù", "english": "Eye", "category": "身体", "emoji": "👁️", "radical": "目", "strokes": 5, "stroke_order": ["竖", "横折", "横", "横", "横"], "origin": {"oracle": "👁", "seal": "目", "meaning": "古人画眼睛形状表示目"}, "story_cn": "眼睛可以看世界，看书、看电视、看风景。保护眼睛很重要！", "story_en": "Eyes can see the world, read books, watch TV, see scenery. Protecting eyes is important!", "words": ["眼睛 yǎn jīng · Eye", "目光 mù guāng · Gaze", "目标 mù biāo · Target", "目前 mù qián · Currently"]},
    {"char": "耳", "pinyin": "ěr", "english": "Ear", "category": "身体", "emoji": "👂", "radical": "耳", "strokes": 6, "stroke_order": ["横", "竖", "竖", "横", "横", "横"], "origin": {"oracle": "👂", "seal": "耳", "meaning": "古人画耳朵形状表示耳"}, "story_cn": "耳朵可以听声音，听音乐、听故事。耳朵是很重要的器官！", "story_en": "Ears can hear sounds, listen to music, hear stories. Ears are important organs!", "words": ["耳朵 ěr duo · Ear", "耳目 ěr mù · Eyes and ears", "耳机 ěr jī · Headphones", "耳语 ěr yǔ · Whisper"]},
    {"char": "心", "pinyin": "xīn", "english": "Heart", "category": "身体", "emoji": "💗", "radical": "心", "strokes": 4, "stroke_order": ["点", "卧钩", "点", "点"], "origin": {"oracle": "💗", "seal": "心", "meaning": "古人画心脏形状表示心"}, "story_cn": "心脏跳动让血液流动。心也代表感情，开心、伤心都是心的感受。", "story_en": "Heart beats to keep blood flowing. Heart also represents feelings - happy, sad are all heart's feelings.", "words": ["心脏 xīn zàng · Heart", "开心 kāi xīn · Happy", "心情 xīn qíng · Mood", "心里 xīn lǐ · In heart"]},
    {"char": "足", "pinyin": "zú", "english": "Foot", "category": "身体", "emoji": "🦶", "radical": "足", "strokes": 7, "stroke_order": ["竖", "横折", "横", "竖", "横", "撇", "捺"], "origin": {"oracle": "🦶", "seal": "足", "meaning": "古人画脚形状表示足"}, "story_cn": "脚可以走路、跑步、跳绳。保护小脚，穿合适的鞋子！", "story_en": "Feet can walk, run, jump rope. Protect little feet, wear proper shoes!", "words": ["脚步 jiǎo bù · Footstep", "足球 zú qiú · Soccer", "足够 zú gòu · Enough", "足迹 zú jì · Footprint"]},
    {"char": "头", "pinyin": "tóu", "english": "Head", "category": "身体", "emoji": "🧠", "radical": "大", "strokes": 5, "stroke_order": ["点", "点", "横", "撇", "点"], "origin": {"oracle": "🧠", "seal": "头", "meaning": "古人画人头形状表示头"}, "story_cn": "头里有大脑，思考问题。头上有眼睛、耳朵、嘴巴、鼻子。", "story_en": "Head has brain for thinking. Head has eyes, ears, mouth, nose.", "words": ["头脑 tóu nǎo · Brain", "头发 tóu fa · Hair", "开头 kāi tóu · Beginning", "点头 diǎn tóu · Nod"]},
    {"char": "一", "pinyin": "yī", "english": "One", "category": "数字", "emoji": "1️⃣", "radical": "一", "strokes": 1, "stroke_order": ["横"], "origin": {"oracle": "一", "seal": "一", "meaning": "古人画一横表示数字一"}, "story_cn": "一是最小的数字，一棵树、一只鸟、一朵花。", "story_en": "One is the smallest number - one tree, one bird, one flower.", "words": ["一个 yī gè · One", "第一 dì yī · First", "一起 yī qǐ · Together", "一样 yī yàng · Same"]},
    {"char": "二", "pinyin": "èr", "english": "Two", "category": "数字", "emoji": "2️⃣", "radical": "二", "strokes": 2, "stroke_order": ["横", "横"], "origin": {"oracle": "二", "seal": "二", "meaning": "古人画两横表示数字二"}, "story_cn": "二是两个东西，两只小鸟、两个苹果。", "story_en": "Two means two things - two birds, two apples.", "words": ["两个 liǎng gè · Two", "第二 dì èr · Second", "二月 èr yuè · February", "二胡 èr hú · Erhu"]},
    {"char": "三", "pinyin": "sān", "english": "Three", "category": "数字", "emoji": "3️⃣", "radical": "一", "strokes": 3, "stroke_order": ["横", "横", "横"], "origin": {"oracle": "三", "seal": "三", "meaning": "古人画三横表示数字三"}, "story_cn": "三是三个东西，三只小猪、三朵花。", "story_en": "Three means three things - three little pigs, three flowers.", "words": ["三个 sān gè · Three", "第三 dì sān · Third", "三月 sān yuè · March", "三心二意 sān xīn èr yì · Half-hearted"]},
    {"char": "四", "pinyin": "sì", "english": "Four", "category": "数字", "emoji": "4️⃣", "radical": "囗", "strokes": 5, "stroke_order": ["竖", "横折", "撇", "竖弯", "横"], "origin": {"oracle": "四", "seal": "四", "meaning": "古人画四条线或方框表示数字四"}, "story_cn": "四是四个东西，四季、四方。", "story_en": "Four means four things - four seasons, four directions.", "words": ["四个 sì gè · Four", "第四 dì sì · Fourth", "四季 sì jì · Four seasons", "四周 sì zhōu · Surroundings"]},
    {"char": "五", "pinyin": "wǔ", "english": "Five", "category": "数字", "emoji": "5️⃣", "radical": "二", "strokes": 4, "stroke_order": ["横", "竖", "横折", "横"], "origin": {"oracle": "五", "seal": "五", "meaning": "古人画交叉形状表示数字五"}, "story_cn": "五是五个东西，五根手指、五颜六色。", "story_en": "Five means five things - five fingers, colorful.", "words": ["五个 wǔ gè · Five", "第五 dì wǔ · Fifth", "五月 wǔ yuè · May", "五彩 wǔ cǎi · Five colors"]},
    {"char": "六", "pinyin": "liù", "english": "Six", "category": "数字", "emoji": "6️⃣", "radical": "八", "strokes": 4, "stroke_order": ["点", "横", "撇", "点"], "origin": {"oracle": "六", "seal": "六", "meaning": "古人画房屋形状表示数字六"}, "story_cn": "六是六个东西，六边形。", "story_en": "Six means six things - hexagon.", "words": ["六个 liù gè · Six", "第六 dì liù · Sixth", "六月 liù yuè · June", "六一 liù yī · June 1st"]},
    {"char": "七", "pinyin": "qī", "english": "Seven", "category": "数字", "emoji": "7️⃣", "radical": "一", "strokes": 2, "stroke_order": ["横", "竖弯钩"], "origin": {"oracle": "七", "seal": "七", "meaning": "古人画十字加弯曲表示数字七"}, "story_cn": "七是七个东西，七彩虹。", "story_en": "Seven means seven things - rainbow has seven colors.", "words": ["七个 qī gè · Seven", "第七 dì qī · Seventh", "七月 qī yuè · July", "七彩 qī cǎi · Seven colors"]},
    {"char": "八", "pinyin": "bā", "english": "Eight", "category": "数字", "emoji": "8️⃣", "radical": "八", "strokes": 2, "stroke_order": ["撇", "捺"], "origin": {"oracle": "八", "seal": "八", "meaning": "古人画分开的两笔表示数字八"}, "story_cn": "八是八个东西，八仙过海。", "story_en": "Eight means eight things - eight immortals cross the sea.", "words": ["八个 bā gè · Eight", "第八 dì bā · Eighth", "八月 bā yuè · August", "八方 bā fāng · Eight directions"]},
    {"char": "九", "pinyin": "jiǔ", "english": "Nine", "category": "数字", "emoji": "9️⃣", "radical": "丿", "strokes": 2, "stroke_order": ["撇", "横折弯钩"], "origin": {"oracle": "九", "seal": "九", "meaning": "古人画弯曲形状表示数字九"}, "story_cn": "九是九个东西，九九重阳。", "story_en": "Nine means nine things - Double Ninth Festival.", "words": ["九个 jiǔ gè · Nine", "第九 dì jiǔ · Ninth", "九月 jiǔ yuè · September", "九九 jiǔ jiǔ · Nine nine"]},
    {"char": "十", "pinyin": "shí", "english": "Ten", "category": "数字", "emoji": "🔟", "radical": "十", "strokes": 2, "stroke_order": ["横", "竖"], "origin": {"oracle": "十", "seal": "十", "meaning": "古人画十字表示数字十"}, "story_cn": "十是十个东西，十全十美。", "story_en": "Ten means ten things - perfect.", "words": ["十个 shí gè · Ten", "第十 dì shí · Tenth", "十月 shí yuè · October", "十分 shí fēn · Very"]},
    {"char": "上", "pinyin": "shàng", "english": "Up/Above", "category": "方位", "emoji": "⬆️", "radical": "一", "strokes": 3, "stroke_order": ["竖", "横", "横"], "origin": {"oracle": "上", "seal": "上", "meaning": "古人画指示符号表示上方"}, "story_cn": "小鸟飞上天空，气球飘上高空。上就是高高的方向。", "story_en": "Birds fly up to sky, balloons float up high. Up means the high direction.", "words": ["上面 shàng miàn · Above", "向上 xiàng shàng · Upward", "上山 shàng shān · Go up mountain", "上课 shàng kè · Attend class"]},
    {"char": "下", "pinyin": "xià", "english": "Down/Below", "category": "方位", "emoji": "⬇️", "radical": "一", "strokes": 3, "stroke_order": ["横", "竖", "点"], "origin": {"oracle": "下", "seal": "下", "meaning": "古人画指示符号表示下方"}, "story_cn": "小虫爬下地面，雨滴落下天空。下就是低低的方向。", "story_en": "Bugs crawl down to ground, raindrops fall down from sky. Down means the low direction.", "words": ["下面 xià miàn · Below", "向下 xiàng xià · Downward", "下山 xià shān · Go down mountain", "下课 xià kè · Class ends"]},
    {"char": "左", "pinyin": "zuǒ", "english": "Left", "category": "方位", "emoji": "⬅️", "radical": "工", "strokes": 5, "stroke_order": ["横", "撇", "横", "竖", "横"], "origin": {"oracle": "左", "seal": "左", "meaning": "古人画左手形状表示左"}, "story_cn": "左手拿东西，左脚走路。左就是身体的一边。", "story_en": "Left hand holds things, left foot walks. Left is one side of the body.", "words": ["左边 zuǒ biān · Left side", "左手 zuǒ shǒu · Left hand", "向左 xiàng zuǒ · To left", "左右 zuǒ yòu · Left and right"]},
    {"char": "右", "pinyin": "yòu", "english": "Right", "category": "方位", "emoji": "➡️", "radical": "口", "strokes": 5, "stroke_order": ["横", "撇", "横", "竖", "横"], "origin": {"oracle": "右", "seal": "右", "meaning": "古人画右手形状表示右"}, "story_cn": "右手写字，右脚踢球。右就是身体的另一边。", "story_en": "Right hand writes, right foot kicks ball. Right is the other side of the body.", "words": ["右边 yòu biān · Right side", "右手 yòu shǒu · Right hand", "向右 xiàng yòu · To right", "左右 zuǒ yòu · Left and right"]},
    {"char": "中", "pinyin": "zhōng", "english": "Middle/Center", "category": "方位", "emoji": "⏺️", "radical": "丨", "strokes": 4, "stroke_order": ["竖", "横折", "横", "竖"], "origin": {"oracle": "中", "seal": "中", "meaning": "古人画旗帜在中间表示中"}, "story_cn": "中间是最中心的位置。中国是我们的国家。", "story_en": "Middle is the center position. China is our country.", "words": ["中间 zhōng jiān · Middle", "中国 zhōng guó · China", "中心 zhōng xīn · Center", "中午 zhōng wǔ · Noon"]},
    {"char": "东", "pinyin": "dōng", "english": "East", "category": "方位", "emoji": "🌅", "radical": "一", "strokes": 5, "stroke_order": ["横", "撇", "竖钩", "撇", "点"], "origin": {"oracle": "东", "seal": "东", "meaning": "古人画太阳升起的方向表示东"}, "story_cn": "太阳从东方升起，东方是太阳出来的方向。", "story_en": "Sun rises from the east, east is where the sun comes out.", "words": ["东方 dōng fāng · East", "东边 dōng biān · East side", "东风 dōng fēng · East wind", "东西 dōng xi · Things"]},
    {"char": "西", "pinyin": "xī", "english": "West", "category": "方位", "emoji": "🌇", "radical": "西", "strokes": 6, "stroke_order": ["横", "竖", "横折", "撇", "点", "撇"], "origin": {"oracle": "西", "seal": "西", "meaning": "古人画太阳落下的方向表示西"}, "story_cn": "太阳从西方落下，西方是太阳消失的方向。", "story_en": "Sun sets in the west, west is where the sun disappears.", "words": ["西方 xī fāng · West", "西边 xī biān · West side", "西风 xī fēng · West wind", "东西 dōng xi · Things"]},
    {"char": "南", "pinyin": "nán", "english": "South", "category": "方位", "emoji": "🧭", "radical": "十", "strokes": 9, "stroke_order": ["横", "竖", "横折钩", "竖", "横", "横", "竖", "横", "横"], "origin": {"oracle": "南", "seal": "南", "meaning": "古人画房屋朝向表示南"}, "story_cn": "南方天气温暖，南方有很多热带水果。", "story_en": "South has warm weather, south has many tropical fruits.", "words": ["南方 nán fāng · South", "南边 nán biān · South side", "南极 nán jí · South Pole", "南风 nán fēng · South wind"]},
    {"char": "北", "pinyin": "běi", "english": "North", "category": "方位", "emoji": "❄️", "radical": "北", "strokes": 5, "stroke_order": ["竖", "横", "提", "撇", "竖弯钩"], "origin": {"oracle": "北", "seal": "北", "meaning": "古人画背靠背的人表示北"}, "story_cn": "北方天气寒冷，北方有美丽的雪景。", "story_en": "North has cold weather, north has beautiful snow scenery.", "words": ["北方 běi fāng · North", "北边 běi biān · North side", "北极 běi jí · North Pole", "北风 běi fēng · North wind"]},
    {"char": "我", "pinyin": "wǒ", "english": "I/Me", "category": "人称", "emoji": "🙋", "radical": "戈", "strokes": 7, "stroke_order": ["撇", "横", "竖钩", "提", "斜钩", "撇", "点"], "origin": {"oracle": "我", "seal": "我", "meaning": "古人画武器形状表示我"}, "story_cn": "我是小朋友，我爱学习，我爱玩耍。", "story_en": "I am a child, I love learning, I love playing.", "words": ["我们 wǒ men · We", "我的 wǒ de · My", "自我 zì wǒ · Self", "小我 xiǎo wǒ · Little me"]},
    {"char": "你", "pinyin": "nǐ", "english": "You", "category": "人称", "emoji": "👉", "radical": "人", "strokes": 7, "stroke_order": ["撇", "竖", "撇", "竖", "横折", "横", "横"], "origin": {"oracle": "你", "seal": "你", "meaning": "古人画人加指示表示你"}, "story_cn": "你是我的好朋友，我们一起玩吧！", "story_en": "You are my good friend, let's play together!", "words": ["你们 nǐ men · You (plural)", "你的 nǐ de · Your", "你好 nǐ hǎo · Hello", "迷你 mí nǐ · Mini"]},
    {"char": "他", "pinyin": "tā", "english": "He/Him", "category": "人称", "emoji": "👨", "radical": "人", "strokes": 5, "stroke_order": ["撇", "竖", "横折钩", "竖", "竖弯钩"], "origin": {"oracle": "他", "seal": "他", "meaning": "古人画人加指示表示他"}, "story_cn": "他是小明，他喜欢踢足球。", "story_en": "He is Xiao Ming, he likes playing soccer.", "words": ["他们 tā men · They", "他的 tā de · His", "他人 tā rén · Others", "其他 qí tā · Other"]},
    {"char": "她", "pinyin": "tā", "english": "She/Her", "category": "人称", "emoji": "👩", "radical": "女", "strokes": 6, "stroke_order": ["撇", "横撇", "竖", "横折钩", "竖", "竖弯钩"], "origin": {"oracle": "她", "seal": "她", "meaning": "古人画女加指示表示她"}, "story_cn": "她是小红，她喜欢画画。", "story_en": "She is Xiao Hong, she likes drawing.", "words": ["她们 tā men · They (female)", "她的 tā de · Her", "她人 tā rén · She person", "其他 qí tā · Other"]},
    {"char": "爸", "pinyin": "bà", "english": "Father", "category": "人称", "emoji": "👨", "radical": "父", "strokes": 8, "stroke_order": ["撇", "点", "撇", "捺", "横折", "横", "横", "横"], "origin": {"oracle": "爸", "seal": "爸", "meaning": "父亲加巴音表示爸"}, "story_cn": "爸爸爱我，爸爸工作辛苦。我爱爸爸！", "story_en": "Father loves me, father works hard. I love father!", "words": ["爸爸 bà ba · Father", "老爸 lǎo bà · Dad", "爸妈 bà mā · Parents", "父爸 fù bà · Father"]},
    {"char": "妈", "pinyin": "mā", "english": "Mother", "category": "人称", "emoji": "👩", "radical": "女", "strokes": 6, "stroke_order": ["撇", "横撇", "竖", "横折钩", "竖", "竖弯钩"], "origin": {"oracle": "妈", "seal": "妈", "meaning": "母亲加马音表示妈"}, "story_cn": "妈妈爱我，妈妈照顾我。我爱妈妈！", "story_en": "Mother loves me, mother takes care of me. I love mother!", "words": ["妈妈 mā ma · Mother", "老妈 lǎo mā · Mom", "爸妈 bà mā · Parents", "妈咪 mā mī · Mommy"]},
    {"char": "爷", "pinyin": "yé", "english": "Grandfather", "category": "人称", "emoji": "👴", "radical": "父", "strokes": 6, "stroke_order": ["撇", "点", "撇", "捺", "横", "竖钩"], "origin": {"oracle": "爷", "seal": "爷", "meaning": "父亲加耶音表示爷"}, "story_cn": "爷爷爱我，爷爷讲故事。我爱爷爷！", "story_en": "Grandpa loves me, grandpa tells stories. I love grandpa!", "words": ["爷爷 yé ye · Grandpa", "大爷 dà yé · Uncle", "老爷 lǎo yé · Master", "爷孙 yé sūn · Grandpa and grandchild"]},
    {"char": "奶", "pinyin": "nǎi", "english": "Grandmother", "category": "人称", "emoji": "👵", "radical": "女", "strokes": 5, "stroke_order": ["撇", "横撇", "竖", "横折钩", "横"], "origin": {"oracle": "奶", "seal": "奶", "meaning": "女性加乃音表示奶"}, "story_cn": "奶奶爱我，奶奶做饭好吃。我爱奶奶！", "story_en": "Grandma loves me, grandma cooks delicious food. I love grandma!", "words": ["奶奶 nǎi nai · Grandma", "牛奶 niú nǎi · Milk", "奶粉 nǎi fěn · Milk powder", "奶奶家 nǎi nai jiā · Grandma's home"]},
    {"char": "走", "pinyin": "zǒu", "english": "Walk/Go", "category": "动作", "emoji": "🚶", "radical": "走", "strokes": 7, "stroke_order": ["横", "竖", "横", "竖", "横", "撇", "捺"], "origin": {"oracle": "走", "seal": "走", "meaning": "古人画人走路形状表示走"}, "story_cn": "小朋友学会走路了！走路上学，走路回家。", "story_en": "Children learn to walk! Walk to school, walk home.", "words": ["走路 zǒu lù · Walk", "走开 zǒu kāi · Go away", "走出 zǒu chū · Walk out", "走进 zǒu jìn · Walk in"]},
    {"char": "跑", "pinyin": "pǎo", "english": "Run", "category": "动作", "emoji": "🏃", "radical": "足", "strokes": 12, "stroke_order": ["竖", "横折", "横", "竖", "横", "撇", "捺", "横折钩", "竖", "横折", "横", "横"], "origin": {"oracle": "跑", "seal": "跑", "meaning": "足加包音表示跑"}, "story_cn": "跑步比赛真有趣！小朋友跑得很快。", "story_en": "Running race is fun! Children run very fast.", "words": ["跑步 pǎo bù · Run", "跑车 pǎo chē · Sports car", "跑开 pǎo kāi · Run away", "跑进 pǎo jìn · Run in"]},
    {"char": "跳", "pinyin": "tiào", "english": "Jump", "category": "动作", "emoji": "🦘", "radical": "足", "strokes": 13, "stroke_order": ["竖", "横折", "横", "竖", "横", "撇", "捺", "竖", "横折", "横", "竖", "横", "横"], "origin": {"oracle": "跳", "seal": "跳", "meaning": "足加兆音表示跳"}, "story_cn": "跳绳、跳高、跳远都是运动。小朋友跳得高！", "story_en": "Jump rope, high jump, long jump are sports. Children jump high!", "words": ["跳绳 tiào shéng · Jump rope", "跳高 tiào gāo · High jump", "跳远 tiào yuǎn · Long jump", "跳舞 tiào wǔ · Dance"]},
    {"char": "吃", "pinyin": "chī", "english": "Eat", "category": "动作", "emoji": "😋", "radical": "口", "strokes": 6, "stroke_order": ["竖", "横折", "横", "撇", "横", "横折弯钩"], "origin": {"oracle": "吃", "seal": "吃", "meaning": "口加乞音表示吃"}, "story_cn": "吃饭时间到了！吃蔬菜、吃水果，健康饮食。", "story_en": "Time to eat! Eat vegetables, eat fruits, healthy diet.", "words": ["吃饭 chī fàn · Eat meal", "好吃 hǎo chī · Delicious", "吃掉 chī diào · Eat up", "吃糖 chī táng · Eat candy"]},
    {"char": "喝", "pinyin": "hē", "english": "Drink", "category": "动作", "emoji": "🥤", "radical": "口", "strokes": 12, "stroke_order": ["竖", "横折", "横", "竖", "横折", "横", "撇", "横钩", "撇", "捺", "竖", "横折"], "origin": {"oracle": "喝", "seal": "喝", "meaning": "口加曷音表示喝"}, "story_cn": "喝水、喝牛奶、喝果汁。多喝水身体好！", "story_en": "Drink water, drink milk, drink juice. Drink more water for good health!", "words": ["喝水 hē shuǐ · Drink water", "喝茶 hē chá · Drink tea", "喝酒 hē jiǔ · Drink alcohol", "喝药 hē yào · Take medicine"]},
    {"char": "笑", "pinyin": "xiào", "english": "Smile", "category": "情感", "emoji": "😊", "radical": "竹", "strokes": 10, "stroke_order": ["撇", "横", "点", "撇", "横", "点", "撇", "撇", "捺", "点"], "origin": {"oracle": "笑", "seal": "笑", "meaning": "竹子下面有夭，表示开心"}, "story_cn": "微笑是最美的表情。每天笑一笑，心情好！", "story_en": "Smile is the most beautiful expression. Smile every day, feel happy!", "words": ["微笑 wēi xiào · Smile", "大笑 dà xiào · Laugh loudly", "笑话 xiào hua · Joke", "笑容 xiào róng · Smile"]},
    {"char": "哭", "pinyin": "kū", "english": "Cry", "category": "情感", "emoji": "😢", "radical": "犬", "strokes": 10, "stroke_order": ["竖", "横折", "横", "竖", "横折", "横", "撇", "捺", "点", "点"], "origin": {"oracle": "哭", "seal": "哭", "meaning": "眼睛流泪表示哭"}, "story_cn": "哭是表达伤心的方式。哭出来会好受一些。", "story_en": "Crying is a way to express sadness. It feels better after crying.", "words": ["哭声 kū shēng · Cry", "哭泣 kū qì · Weep", "哭脸 kū liǎn · Sad face", "哭啼 kū tí · Whimper"]},
    {"char": "爱", "pinyin": "ài", "english": "Love", "category": "情感", "emoji": "❤️", "radical": "爫", "strokes": 10, "stroke_order": ["撇", "点", "点", "撇", "点", "横撇", "横", "撇", "撇", "捺"], "origin": {"oracle": "爱", "seal": "爱", "meaning": "心中有喜爱的人"}, "story_cn": "爱是温暖的感觉。我爱爸爸妈妈，我爱这个世界！", "story_en": "Love is a warm feeling. I love my parents, I love the world!", "words": ["爱心 ài xīn · Love", "爱情 ài qíng · Love", "爱护 ài hù · Cherish", "可爱 kě ài · Cute"]},
    {"char": "喜", "pinyin": "xǐ", "english": "Happy", "category": "情感", "emoji": "😄", "radical": "士", "strokes": 12, "stroke_order": ["横", "竖", "横折", "横", "点", "撇", "横", "竖", "横折", "横", "竖钩", "撇", "点"], "origin": {"oracle": "喜", "seal": "喜", "meaning": "古人表示高兴"}, "story_cn": "喜事就是开心的事。过年是喜事，生日也是喜事！", "story_en": "Happy events are joyful things. Chinese New Year is happy, birthday is happy!", "words": ["喜欢 xǐ huān · Like", "高兴 gāo xìng · Happy", "喜事 xǐ shì · Happy event", "喜庆 xǐ qìng · Festive"]},
    {"char": "乐", "pinyin": "lè", "english": "Joy", "category": "情感", "emoji": "🎊", "radical": "丿", "strokes": 5, "stroke_order": ["撇", "竖折", "竖钩", "撇", "点"], "origin": {"oracle": "乐", "seal": "乐", "meaning": "古人表示快乐"}, "story_cn": "快乐是美好的感觉。唱歌、跳舞、玩耍都很快乐！", "story_en": "Joy is a wonderful feeling. Singing, dancing, playing are all joyful!", "words": ["快乐 kuài lè · Happy", "欢乐 huān lè · Joy", "乐园 lè yuán · Amusement park", "乐意 lè yì · Willing"]},
    {"char": "好", "pinyin": "hǎo", "english": "Good", "category": "情感", "emoji": "👍", "radical": "女", "strokes": 6, "stroke_order": ["撇", "横撇", "竖", "横折", "横", "横"], "origin": {"oracle": "好", "seal": "好", "meaning": "女子在一起表示美好"}, "story_cn": "好就是很棒的意思。好人、好事、好心情！", "story_en": "Good means excellent. Good people, good things, good mood!", "words": ["好人 hǎo rén · Good person", "好事 hǎo shì · Good thing", "好看 hǎo kàn · Good looking", "好玩 hǎo wán · Fun"]},
    {"char": "米", "pinyin": "mǐ", "english": "Rice", "category": "食物", "emoji": "🍚", "radical": "米", "strokes": 6, "stroke_order": ["点", "撇", "横", "竖", "撇", "捺"], "origin": {"oracle": "米", "seal": "米", "meaning": "古人画米粒形状表示米"}, "story_cn": "米饭是主食。大米香喷喷，小朋友要好好吃饭！", "story_en": "Rice is the staple food. Rice smells good, children should eat well!", "words": ["米饭 mǐ fàn · Rice", "大米 dà mǐ · Rice", "小米 xiǎo mǐ · Millet", "玉米 yù mǐ · Corn"]},
    {"char": "面", "pinyin": "miàn", "english": "Noodle", "category": "食物", "emoji": "🍜", "radical": "面", "strokes": 9, "stroke_order": ["横", "竖", "横折", "横", "竖", "撇", "点", "撇", "捺"], "origin": {"oracle": "面", "seal": "面", "meaning": "古人画面粉形状表示面"}, "story_cn": "面条长长的，可以做很多好吃的。牛肉面、鸡蛋面都很好吃！", "story_en": "Noodles are long, can make many delicious dishes. Beef noodles, egg noodles are delicious!", "words": ["面条 miàn tiáo · Noodles", "面包 miàn bāo · Bread", "面粉 miàn fěn · Flour", "方便面 fāng biàn miàn · Instant noodles"]},
    {"char": "肉", "pinyin": "ròu", "english": "Meat", "category": "食物", "emoji": "🥩", "radical": "肉", "strokes": 6, "stroke_order": ["竖", "横折钩", "撇", "点", "撇", "点"], "origin": {"oracle": "肉", "seal": "肉", "meaning": "古人画肉的形状表示肉"}, "story_cn": "肉很有营养，能帮助小朋友长大。鸡肉、鱼肉都很好！", "story_en": "Meat is nutritious, helps children grow. Chicken, fish are all good!", "words": ["猪肉 zhū ròu · Pork", "牛肉 niú ròu · Beef", "鸡肉 jī ròu · Chicken", "鱼肉 yú ròu · Fish"]},
    {"char": "菜", "pinyin": "cài", "english": "Vegetable", "category": "食物", "emoji": "🥬", "radical": "艹", "strokes": 11, "stroke_order": ["横", "竖", "竖", "横", "撇", "竖", "横折", "竖", "撇", "捺", "点"], "origin": {"oracle": "菜", "seal": "菜", "meaning": "草本植物可食用表示菜"}, "story_cn": "蔬菜很健康，有很多维生素。多吃蔬菜身体棒！", "story_en": "Vegetables are healthy, have many vitamins. Eat more vegetables for good health!", "words": ["蔬菜 shū cài · Vegetables", "白菜 bái cài · Chinese cabbage", "青菜 qīng cài · Green vegetables", "买菜 mǎi cài · Buy vegetables"]},
    {"char": "红", "pinyin": "hóng", "english": "Red", "category": "颜色", "emoji": "🔴", "radical": "纟", "strokes": 6, "stroke_order": ["撇折", "撇折", "提", "横", "竖", "横"], "origin": {"oracle": "红", "seal": "红", "meaning": "丝线染成红色"}, "story_cn": "红色是喜庆的颜色。过年时红灯笼、红鞭炮，很热闹！", "story_en": "Red is a festive color. Red lanterns, red firecrackers during Chinese New Year!", "words": ["红色 hóng sè · Red", "红花 hóng huā · Red flower", "红旗 hóng qí · Red flag", "红火 hóng huǒ · Prosperous"]},
    {"char": "黄", "pinyin": "huáng", "english": "Yellow", "category": "颜色", "emoji": "🟡", "radical": "黄", "strokes": 11, "stroke_order": ["横", "竖", "竖", "横", "竖", "横折", "横", "竖", "撇", "点"], "origin": {"oracle": "黄", "seal": "黄", "meaning": "古人画玉佩表示黄色"}, "story_cn": "黄色是阳光的颜色。秋天的树叶变黄了，很漂亮！", "story_en": "Yellow is the color of sunshine. Autumn leaves turn yellow, very beautiful!", "words": ["黄色 huáng sè · Yellow", "黄金 huáng jīn · Gold", "黄河 huáng hé · Yellow River", "黄昏 huáng hūn · Dusk"]},
    {"char": "蓝", "pinyin": "lán", "english": "Blue", "category": "颜色", "emoji": "🔵", "radical": "艹", "strokes": 13, "stroke_order": ["横", "竖", "竖", "竖", "竖折", "竖", "横", "竖", "横折", "横", "横", "撇", "竖"], "origin": {"oracle": "蓝", "seal": "蓝", "meaning": "蓝草可以染蓝色"}, "story_cn": "蓝色是天空和大海的颜色。蓝色让人感觉很舒服！", "story_en": "Blue is the color of sky and sea. Blue makes people feel comfortable!", "words": ["蓝色 lán sè · Blue", "蓝天 lán tiān · Blue sky", "蓝图 lán tú · Blueprint", "蓝色 lán sè · Blue"]},
    {"char": "绿", "pinyin": "lǜ", "english": "Green", "category": "颜色", "emoji": "🟢", "radical": "纟", "strokes": 11, "stroke_order": ["撇折", "撇折", "提", "横折", "横", "竖钩", "点", "撇", "点"], "origin": {"oracle": "绿", "seal": "绿", "meaning": "丝线染成绿色"}, "story_cn": "绿色是小草和树叶的颜色。绿色代表生命！", "story_en": "Green is the color of grass and leaves. Green represents life!", "words": ["绿色 lǜ sè · Green", "草地 cǎo dì · Grassland", "绿叶 lǜ yè · Green leaf", "绿树 lǜ shù · Green tree"]},
    {"char": "白", "pinyin": "bái", "english": "White", "category": "颜色", "emoji": "⚪", "radical": "白", "strokes": 5, "stroke_order": ["撇", "竖", "横折", "横", "横"], "origin": {"oracle": "白", "seal": "白", "meaning": "古人画白色表示白"}, "story_cn": "白色是雪和云朵的颜色。白色很纯洁！", "story_en": "White is the color of snow and clouds. White is pure!", "words": ["白色 bái sè · White", "白云 bái yún · White cloud", "白雪 bái xuě · White snow", "白天 bái tiān · Daytime"]},
    {"char": "黑", "pinyin": "hēi", "english": "Black", "category": "颜色", "emoji": "⚫", "radical": "黑", "strokes": 12, "stroke_order": ["竖", "横折", "点", "撇", "横", "竖", "横折", "横", "横", "点", "点", "点"], "origin": {"oracle": "黑", "seal": "黑", "meaning": "古人画黑色表示黑"}, "story_cn": "黑色是夜晚的颜色。黑夜很美，有星星和月亮！", "story_en": "Black is the color of night. Night is beautiful with stars and moon!", "words": ["黑色 hēi sè · Black", "黑夜 hēi yè · Night", "黑板 hēi bǎn · Blackboard", "黑发 hēi fà · Black hair"]},
    {"char": "学", "pinyin": "xué", "english": "Learn", "category": "动作", "emoji": "📚", "radical": "子", "strokes": 8, "stroke_order": ["点", "点", "撇", "点", "横钩", "横撇", "竖钩", "横"], "origin": {"oracle": "学", "seal": "学", "meaning": "古人学习的样子"}, "story_cn": "学习很有趣！每天学一点，知识多一点。", "story_en": "Learning is fun! Learn a little every day, gain more knowledge.", "words": ["学习 xué xí · Learn", "学生 xué shēng · Student", "学校 xué xiào · School", "学问 xué wèn · Knowledge"]},
    {"char": "书", "pinyin": "shū", "english": "Book", "category": "物品", "emoji": "📖", "radical": "乙", "strokes": 4, "stroke_order": ["横折", "横折钩", "竖", "点"], "origin": {"oracle": "书", "seal": "书", "meaning": "古人书写的样子"}, "story_cn": "书是知识的宝库。读书可以学到很多东西！", "story_en": "Books are treasure troves of knowledge. Reading can learn many things!", "words": ["书本 shū běn · Book", "看书 kàn shū · Read", "书包 shū bāo · School bag", "书店 shū diàn · Bookstore"]},
    {"char": "家", "pinyin": "jiā", "english": "Home", "category": "物品", "emoji": "🏠", "radical": "宀", "strokes": 10, "stroke_order": ["点", "点", "横钩", "横", "撇", "弯钩", "撇", "撇", "撇", "捺"], "origin": {"oracle": "家", "seal": "家", "meaning": "房子里有猪表示家"}, "story_cn": "家是温暖的港湾。爸爸妈妈和我，组成幸福的家！", "story_en": "Home is a warm harbor. Mom, dad and me, we make a happy family!", "words": ["家里 jiā lǐ · Home", "家人 jiā rén · Family", "回家 huí jiā · Go home", "大家 dà jiā · Everyone"]},
]

stories = [
    {"id": 1, "title_cn": "太阳和月亮的故事", "title_en": "The Story of Sun and Moon", "content_cn": "很久很久以前，天上只有一个太阳。太阳每天都很辛苦地工作，把光和热带给大地。有一天，太阳觉得太累了，就去找月亮帮忙。月亮说：\"好的，我来帮你！\"于是，太阳白天工作，月亮晚上工作，轮流守护着大地。从此，白天有温暖的阳光，夜晚有柔和的月光。", "content_en": "Long long ago, there was only the sun in the sky. The sun worked hard every day, bringing light and warmth to the earth. One day, the sun felt too tired and went to ask the moon for help. The moon said, 'Okay, I'll help you!' So the sun works during the day and the moon works at night, taking turns to guard the earth. Since then, there's warm sunshine during the day and soft moonlight at night.", "difficulty": 1, "characters": ["日", "月", "天", "地", "光", "热", "白", "晚"]},
    {"id": 2, "title_cn": "三只小猪", "title_en": "Three Little Pigs", "content_cn": "猪妈妈有三只小猪。有一天，猪妈妈对小猪们说：\"孩子们，你们长大了，应该自己盖房子住了。\"老大用稻草盖了一间房子，老二用木头盖了一间房子，老三用砖头盖了一间房子。一只大灰狼来了，吹倒了老大和老二的房子，但是吹不倒老三的砖房子。三只小猪都躲进了砖房子里，大灰狼再也没办法了。", "content_en": "Mother pig has three little pigs. One day, Mother Pig said to the little pigs, 'Children, you've grown up, you should build your own houses to live in.' The oldest pig built a house with straw, the second pig built a house with wood, and the youngest pig built a house with bricks. A big bad wolf came, blew down the oldest and second pig's houses, but couldn't blow down the youngest pig's brick house. All three little pigs hid in the brick house, and the wolf had no way.", "difficulty": 1, "characters": ["三", "小", "猪", "房", "子", "草", "木", "砖"]},
    {"id": 3, "title_cn": "小鸟找妈妈", "title_en": "Little Bird Finds Mom", "content_cn": "春天来了，小鸟从蛋里孵出来了。它睁开眼睛，看到蓝蓝的天空和绿绿的草地。小鸟问：\"妈妈在哪里？\"蝴蝶说：\"你的妈妈有翅膀。\"蜜蜂说：\"你的妈妈会唱歌。\"小鸟飞呀飞，终于找到了鸟妈妈。鸟妈妈说：\"孩子，妈妈在这里！\"小鸟高兴地扑进妈妈的怀里。", "content_en": "Spring came, and the little bird hatched from the egg. It opened its eyes and saw the blue sky and green grass. The little bird asked, 'Where is Mom?' The butterfly said, 'Your mom has wings.' The bee said, 'Your mom can sing.' The little bird flew and flew, finally finding Bird Mom. Bird Mom said, 'Child, Mom is here!' The little bird happily flew into Mom's arms.", "difficulty": 1, "characters": ["鸟", "妈", "妈", "天", "空", "草", "地", "飞"]},
    {"id": 4, "title_cn": "小熊钓鱼", "title_en": "Little Bear Goes Fishing", "content_cn": "小熊拿着鱼竿来到河边钓鱼。他等啊等，鱼就是不上钩。小熊有点着急了。这时，一只蝴蝶飞过来，小熊放下鱼竿去追蝴蝶。追了一会儿，蝴蝶飞走了，小熊又回到河边。他等啊等，终于钓到了一条大鱼！小熊高兴极了，提着大鱼回家了。", "content_en": "Little Bear took a fishing rod and went fishing by the river. He waited and waited, but the fish wouldn't bite. Little Bear got a little anxious. Just then, a butterfly flew by, and Little Bear put down his rod to chase the butterfly. After chasing for a while, the butterfly flew away, and Little Bear returned to the river. He waited and waited, finally catching a big fish! Little Bear was overjoyed and carried the big fish home.", "difficulty": 1, "characters": ["熊", "鱼", "河", "竿", "等", "蝴", "蝶", "追"]},
    {"id": 5, "title_cn": "小兔采蘑菇", "title_en": "Little Rabbit Picks Mushrooms", "content_cn": "秋天到了，小兔子背着篮子去森林里采蘑菇。森林里的蘑菇真多啊！有红色的、黄色的、白色的。妈妈告诉小兔：\"彩色的蘑菇有毒，不能吃。\"小兔只采白色的蘑菇。采着采着，小兔发现了一个又大又白的蘑菇。小兔高兴地采下来，放进篮子里。回家后，妈妈夸小兔是个聪明的孩子。", "content_en": "Autumn arrived, and Little Rabbit carried a basket to pick mushrooms in the forest. There were so many mushrooms in the forest! Red ones, yellow ones, white ones. Mom told Little Rabbit, 'Colorful mushrooms are poisonous, don't eat them.' Little Rabbit only picked white mushrooms. While picking, Little Rabbit found a big white mushroom. Little Rabbit happily picked it and put it in the basket. After returning home, Mom praised Little Rabbit as a smart child.", "difficulty": 2, "characters": ["兔", "蘑", "菇", "森", "林", "采", "篮", "毒"]},
    {"id": 6, "title_cn": "小蚂蚁搬西瓜", "title_en": "Little Ants Move Watermelon", "content_cn": "一只小蚂蚁在草地上发现了一块大西瓜。西瓜又大又甜，小蚂蚁搬不动。于是，小蚂蚁跑回蚁巢，叫来许多小伙伴。大家一起用力，把西瓜搬回了家。蚂蚁们高兴地分享着甜甜的西瓜，它们说：\"团结就是力量！\"", "content_en": "A little ant found a big watermelon on the grass. The watermelon was big and sweet, and the little ant couldn't carry it. So the little ant ran back to the nest and called many friends. Everyone worked together to carry the watermelon home. The ants happily shared the sweet watermelon, saying, 'Unity is strength!'", "difficulty": 2, "characters": ["蚂", "蚁", "西", "瓜", "搬", "力", "团", "结"]},
    {"id": 7, "title_cn": "雪人不见了", "title_en": "The Snowman Disappeared", "content_cn": "冬天来了，下了一场大雪。小朋友们堆了一个漂亮的雪人。雪人有圆圆的脑袋，大大的肚子，还有一双用树枝做的手。小朋友们每天都来看雪人。春天来了，天气变暖了。有一天，小朋友们发现雪人不见了，地上只剩下一滩水。妈妈说：\"雪人变成了水，又变成了水蒸气，飞到天上去了。\"", "content_en": "Winter came, and it snowed heavily. The children built a beautiful snowman. The snowman had a round head, a big belly, and two hands made of branches. The children came to see the snowman every day. Spring came, and the weather warmed up. One day, the children found the snowman was gone, only a puddle of water was left on the ground. Mom said, 'The snowman turned into water, then into water vapor, and flew up to the sky.'", "difficulty": 2, "characters": ["雪", "人", "冬", "天", "春", "水", "汽", "飞"]},
    {"id": 8, "title_cn": "小猫钓鱼", "title_en": "Little Cat Goes Fishing", "content_cn": "小猫跟着妈妈去河边钓鱼。小猫看到蜻蜓飞过来，就放下鱼竿去追蜻蜓。追了一会儿，蜻蜓飞走了，小猫什么也没追到。回到河边，妈妈已经钓到了一条鱼。小猫有点不好意思。妈妈说：\"做事情要专心，不能三心二意。\"小猫点点头，专心地钓鱼。过了一会儿，小猫也钓到了一条小鱼！", "content_en": "Little Cat followed Mom to the river to fish. Little Cat saw a dragonfly fly by and put down the rod to chase it. After chasing for a while, the dragonfly flew away, and Little Cat caught nothing. Returning to the river, Mom had already caught a fish. Little Cat felt a little embarrassed. Mom said, 'You must concentrate when doing things, not be half-hearted.' Little Cat nodded and focused on fishing. After a while, Little Cat also caught a small fish!", "difficulty": 2, "characters": ["猫", "钓", "鱼", "蜻", "蜓", "专", "心", "追"]},
    {"id": 9, "title_cn": "龟兔赛跑", "title_en": "The Tortoise and the Hare", "content_cn": "乌龟和兔子决定比赛跑步。兔子跑得很快，一会儿就把乌龟远远地甩在了后面。兔子觉得乌龟太慢了，就躺在路边睡着了。乌龟虽然跑得慢，但是一直不停地爬。等兔子醒来的时候，乌龟已经快到终点了。兔子赶紧跑过去，但已经来不及了。乌龟赢得了比赛！", "content_en": "The tortoise and the hare decided to race. The hare ran very fast, leaving the tortoise far behind in no time. The hare thought the tortoise was too slow, so he lay down by the road and fell asleep. Although the tortoise ran slowly, he kept crawling without stopping. When the hare woke up, the tortoise was almost at the finish line. The hare ran quickly, but it was too late. The tortoise won the race!", "difficulty": 3, "characters": ["龟", "兔", "赛", "跑", "快", "慢", "睡", "赢"]},
    {"id": 10, "title_cn": "小蝌蚪找妈妈", "title_en": "Little Tadpoles Find Mom", "content_cn": "池塘里有一群小蝌蚪，它们长着大大的脑袋和长长的尾巴。小蝌蚪问鲤鱼阿姨：\"阿姨，您知道我们的妈妈在哪里吗？\"鲤鱼阿姨说：\"你们的妈妈有四条腿，宽嘴巴。\"小蝌蚪游啊游，看到了一只乌龟。它们说：\"妈妈！\"乌龟说：\"我不是你们的妈妈，你们的妈妈是青蛙。\"小蝌蚪继续游，终于找到了青蛙妈妈。", "content_en": "There was a group of little tadpoles in the pond, with big heads and long tails. The little tadpoles asked Aunt Carp, 'Aunt, do you know where our mom is?' Aunt Carp said, 'Your mom has four legs and a wide mouth.' The little tadpoles swam and swam, and saw a turtle. They said, 'Mom!' The turtle said, 'I'm not your mom, your mom is a frog.' The little tadpoles continued swimming and finally found Frog Mom.", "difficulty": 3, "characters": ["蝌", "蚪", "找", "妈", "蛙", "鱼", "龟", "腿"]},
    {"id": 11, "title_cn": "乌鸦喝水", "title_en": "The Crow Drinks Water", "content_cn": "一只乌鸦口渴了，到处找水喝。它发现了一个瓶子，里面有一些水。但是瓶子很高，乌鸦够不着。乌鸦想了想，看到旁边有许多小石子。它把小石子一颗一颗放进瓶子里。瓶子里的水位慢慢升高，乌鸦终于喝到水了！", "content_en": "A crow was thirsty and looked everywhere for water. It found a bottle with some water in it. But the bottle was tall, and the crow couldn't reach. The crow thought for a while and saw many small stones nearby. It put the small stones into the bottle one by one. The water level in the bottle slowly rose, and the crow finally drank the water!", "difficulty": 3, "characters": ["乌", "鸦", "喝", "水", "瓶", "石", "子", "高"]},
    {"id": 12, "title_cn": "猴子捞月", "title_en": "Monkeys Fish for the Moon", "content_cn": "一群猴子在树上玩耍。一只小猴看到井里有一个月亮，大声喊：\"不好了！月亮掉进井里了！\"老猴说：\"我们把月亮捞上来吧！\"于是，猴子们一个接一个地挂在树上，最下面的小猴伸手去捞月亮。可是，它刚碰到水面，月亮就碎了。老猴抬头一看，月亮还好好地挂在天上呢！", "content_en": "A group of monkeys were playing in the trees. A little monkey saw a moon in the well and shouted, 'Oh no! The moon fell into the well!' The old monkey said, 'Let's fish the moon out!' So the monkeys hung from the tree one by one, and the little monkey at the bottom reached out to fish for the moon. But as soon as it touched the water, the moon broke into pieces. The old monkey looked up and saw the moon was still hanging in the sky!", "difficulty": 3, "characters": ["猴", "子", "捞", "月", "井", "树", "挂", "碎"]}
]

reading = [
    {"id": 1, "title_cn": "春天来了", "title_en": "Spring is Coming", "content_cn": "春天来了！小草绿了，花儿开了。小鸟在树上唱歌，蝴蝶在花丛中跳舞。小朋友们脱掉棉袄，跑到公园里玩耍。春天真美好！", "content_en": "Spring is coming! The grass turns green, flowers bloom. Birds sing in the trees, butterflies dance among flowers. Children take off their cotton-padded jackets and run to play in the park. Spring is so beautiful!", "difficulty": 1, "words": ["春", "天", "草", "花", "鸟", "树", "歌", "舞"]},
    {"id": 2, "title_cn": "我的家人", "title_en": "My Family", "content_cn": "我家有爸爸、妈妈、爷爷、奶奶和我。爸爸很高，妈妈很美。爷爷喜欢下棋，奶奶喜欢做饭。我爱我的家人！", "content_en": "There are dad, mom, grandpa, grandma and me in my family. Dad is tall, mom is beautiful. Grandpa likes playing chess, grandma likes cooking. I love my family!", "difficulty": 1, "words": ["家", "人", "爸", "妈", "爷", "奶", "爱", "我"]},
    {"id": 3, "title_cn": "小动物们", "title_en": "Little Animals", "content_cn": "小猫喵喵叫，小狗汪汪叫。小鸡叽叽叽，小鸭嘎嘎嘎。小羊咩咩咩，小牛哞哞哞。小动物们真可爱！", "content_en": "Little cat meows, little dog barks. Little chick cheeps, little duck quacks. Little sheep bleats, little cow moos. Little animals are so cute!", "difficulty": 1, "words": ["猫", "狗", "鸡", "鸭", "羊", "牛", "叫", "爱"]},
    {"id": 4, "title_cn": "水果乐园", "title_en": "Fruit Paradise", "content_cn": "苹果红，香蕉黄。葡萄紫，橙子橙。西瓜大，草莓小。水果甜，营养好！", "content_en": "Apple is red, banana is yellow. Grape is purple, orange is orange. Watermelon is big, strawberry is small. Fruits are sweet, nutritious!", "difficulty": 2, "words": ["苹", "果", "香", "蕉", "葡", "萄", "西", "瓜"]},
    {"id": 5, "title_cn": "颜色歌", "title_en": "Color Song", "content_cn": "蓝蓝的天空白白的云，红红的花朵绿绿的草。黄黄的香蕉紫紫的葡萄，彩色的世界真美好！", "content_en": "Blue sky white clouds, red flowers green grass. Yellow bananas purple grapes, colorful world is so beautiful!", "difficulty": 2, "words": ["蓝", "天", "白", "云", "红", "花", "绿", "草"]},
    {"id": 6, "title_cn": "数字歌", "title_en": "Number Song", "content_cn": "一二三四五，上山打老虎。老虎没打到，打到小松鼠。松鼠有几只？让我数一数。一二三四五！", "content_en": "One two three four five, go up the mountain to fight tiger. Didn't catch tiger, caught little squirrel. How many squirrels? Let me count. One two three four five!", "difficulty": 2, "words": ["一", "二", "三", "四", "五", "山", "虎", "松"]},
    {"id": 7, "title_cn": "我爱学习", "title_en": "I Love Learning", "content_cn": "我喜欢读书，也喜欢写字。老师教我们认字，教我们画画。每天学习新知识，我真开心！", "content_en": "I like reading, I also like writing. Teacher teaches us to read characters, teaches us to draw. Learning new knowledge every day, I'm so happy!", "difficulty": 2, "words": ["学", "习", "书", "字", "老", "师", "画", "知"]},
    {"id": 8, "title_cn": "运动会", "title_en": "Sports Day", "content_cn": "学校开运动会，小朋友们来比赛。有的跑步，有的跳绳，有的跳高。大家都很努力，加油加油！", "content_en": "The school holds a sports meeting, children come to compete. Some run, some jump rope, some high jump. Everyone works hard, go go go!", "difficulty": 3, "words": ["运", "动", "会", "跑", "跳", "绳", "高", "加"]},
    {"id": 9, "title_cn": "下雨天", "title_en": "Rainy Day", "content_cn": "哗啦啦，下雨了！小朋友们穿上雨衣，打起雨伞。雨水落在地上，溅起一朵朵水花。小青蛙在池塘里高兴地唱歌。", "content_en": "Pitter-patter, it's raining! Children put on raincoats, hold umbrellas. Rain falls on the ground, splashing water flowers. Little frogs sing happily in the pond.", "difficulty": 3, "words": ["雨", "天", "衣", "伞", "水", "花", "蛙", "唱"]},
    {"id": 10, "title_cn": "美丽的夜晚", "title_en": "Beautiful Night", "content_cn": "夜晚来了，月亮升起来了。星星在天上眨眼睛，萤火虫在草丛中飞舞。小朋友们听着故事，进入甜甜的梦乡。", "content_en": "Night comes, the moon rises. Stars twinkle in the sky, fireflies dance in the grass. Children listen to stories and fall into sweet dreams.", "difficulty": 3, "words": ["夜", "晚", "月", "星", "萤", "火", "梦", "乡"]}
]

radicals = [
    {"radical": "一", "meaning": "横画", "pinyin": "yī", "examples": ["一", "二", "三", "天", "大"]},
    {"radical": "丨", "meaning": "竖画", "pinyin": "gǔn", "examples": ["中", "丰", "串", "事", "书"]},
    {"radical": "丿", "meaning": "撇画", "pinyin": "piě", "examples": ["人", "大", "牛", "毛", "手"]},
    {"radical": "丶", "meaning": "点画", "pinyin": "zhǔ", "examples": ["主", "为", "义", "火", "心"]},
    {"radical": "乙", "meaning": "折画", "pinyin": "yǐ", "examples": ["九", "也", "乞", "孔", "书"]},
    {"radical": "二", "meaning": "二横", "pinyin": "èr", "examples": ["二", "云", "亏", "亚", "些"]},
    {"radical": "人", "meaning": "人", "pinyin": "rén", "examples": ["人", "大", "个", "从", "众"]},
    {"radical": "儿", "meaning": "儿", "pinyin": "ér", "examples": ["儿", "元", "兄", "光", "先"]},
    {"radical": "亠", "meaning": "点横", "pinyin": "tóu", "examples": ["六", "交", "京", "言", "立"]},
    {"radical": "大", "meaning": "大", "pinyin": "dà", "examples": ["大", "天", "太", "夫", "失"]},
    {"radical": "小", "meaning": "小", "pinyin": "xiǎo", "examples": ["小", "少", "尖", "光", "当"]},
    {"radical": "口", "meaning": "口", "pinyin": "kǒu", "examples": ["口", "日", "目", "田", "国"]},
    {"radical": "日", "meaning": "日", "pinyin": "rì", "examples": ["日", "明", "时", "星", "春"]},
    {"radical": "月", "meaning": "月", "pinyin": "yuè", "examples": ["月", "明", "有", "朋", "背"]},
    {"radical": "水", "meaning": "水", "pinyin": "shuǐ", "examples": ["水", "河", "海", "江", "没"]},
    {"radical": "火", "meaning": "火", "pinyin": "huǒ", "examples": ["火", "炎", "烈", "灯", "烧"]},
    {"radical": "土", "meaning": "土", "pinyin": "tǔ", "examples": ["土", "地", "城", "堆", "坡"]},
    {"radical": "山", "meaning": "山", "pinyin": "shān", "examples": ["山", "出", "岁", "峰", "岭"]},
    {"radical": "石", "meaning": "石", "pinyin": "shí", "examples": ["石", "破", "矿", "码", "硬"]},
    {"radical": "木", "meaning": "木", "pinyin": "mù", "examples": ["木", "林", "森", "树", "村"]},
    {"radical": "艹", "meaning": "草字头", "pinyin": "cǎo", "examples": ["草", "花", "菜", "蓝", "苦"]},
    {"radical": "竹", "meaning": "竹字头", "pinyin": "zhú", "examples": ["笑", "笔", "答", "等", "第"]},
    {"radical": "亻", "meaning": "单人旁", "pinyin": "rén", "examples": ["他", "你", "们", "什", "住"]},
    {"radical": "女", "meaning": "女字旁", "pinyin": "nǚ", "examples": ["女", "妈", "好", "她", "姓"]},
    {"radical": "子", "meaning": "子字旁", "pinyin": "zǐ", "examples": ["子", "学", "孩", "字", "孙"]}
]

idioms = [
    {"idiom": "一心一意", "pinyin": "yī xīn yī yì", "meaning": "专心致志，只有一个心思", "story": "做事情要一心一意，不能三心二意。"},
    {"idiom": "三心二意", "pinyin": "sān xīn èr yì", "meaning": "心思不专一，犹豫不决", "story": "小猫钓鱼三心二意，结果一条鱼也没钓到。"},
    {"idiom": "五颜六色", "pinyin": "wǔ yán liù sè", "meaning": "形容色彩丰富多样", "story": "春天来了，花园里开着五颜六色的花朵。"},
    {"idiom": "七上八下", "pinyin": "qī shàng bā xià", "meaning": "形容心里慌乱不安", "story": "考试前，小明心里七上八下的。"},
    {"idiom": "九牛一毛", "pinyin": "jiǔ niú yī máo", "meaning": "比喻数量极少，微不足道", "story": "这点钱对他来说，简直是九牛一毛。"},
    {"idiom": "十全十美", "pinyin": "shí quán shí měi", "meaning": "十分完美，没有缺陷", "story": "世界上没有十全十美的事物。"},
    {"idiom": "画蛇添足", "pinyin": "huà shé tiān zú", "meaning": "做多余的事，反而不恰当", "story": "已经很好了，不要再画蛇添足了。"},
    {"idiom": "对牛弹琴", "pinyin": "duì niú tán qín", "meaning": "对不懂道理的人讲道理", "story": "跟他说这个，简直是对牛弹琴。"},
    {"idiom": "井底之蛙", "pinyin": "jǐng dǐ zhī wā", "meaning": "比喻眼界狭窄的人", "story": "不要做井底之蛙，要多出去看看。"},
    {"idiom": "亡羊补牢", "pinyin": "wáng yáng bǔ láo", "meaning": "出了问题及时补救", "story": "亡羊补牢，为时不晚。"},
    {"idiom": "守株待兔", "pinyin": "shǒu zhū dài tù", "meaning": "比喻不主动努力", "story": "不要守株待兔，要主动争取。"},
    {"idiom": "掩耳盗铃", "pinyin": "yǎn ěr dào líng", "meaning": "自欺欺人", "story": "这种做法就是掩耳盗铃。"},
    {"idiom": "拔苗助长", "pinyin": "bá miáo zhù zhǎng", "meaning": "急于求成，反而坏事", "story": "学习不能拔苗助长，要循序渐进。"},
    {"idiom": "刻舟求剑", "pinyin": "kè zhōu qiú jiàn", "meaning": "拘泥固执，不知变通", "story": "情况变了，不能再刻舟求剑了。"},
    {"idiom": "画龙点睛", "pinyin": "huà lóng diǎn jīng", "meaning": "关键处加一笔，使效果更好", "story": "这篇文章的结尾真是画龙点睛！"},
    {"idiom": "叶公好龙", "pinyin": "yè gōng hào lóng", "meaning": "表面爱好，实际害怕", "story": "他只是叶公好龙，并不是真的喜欢。"},
    {"idiom": "惊弓之鸟", "pinyin": "jīng gōng zhī niǎo", "meaning": "受过惊吓后容易惊慌", "story": "他现在像惊弓之鸟一样，一点声音都害怕。"},
    {"idiom": "杯弓蛇影", "pinyin": "bēi gōng shé yǐng", "meaning": "疑神疑鬼，自相惊扰", "story": "别杯弓蛇影了，那只是一根绳子。"},
    {"idiom": "狐假虎威", "pinyin": "hú jiǎ hǔ wēi", "meaning": "依仗别人的势力欺压人", "story": "他只是狐假虎威，没什么了不起。"},
    {"idiom": "鹬蚌相争", "pinyin": "yù bàng xiāng zhēng", "meaning": "双方相争，两败俱伤", "story": "你们别鹬蚌相争，让别人得利。"},
    {"idiom": "塞翁失马", "pinyin": "sài wēng shī mǎ", "meaning": "坏事可能变成好事", "story": "塞翁失马，焉知非福。"},
    {"idiom": "亡羊补牢", "pinyin": "wáng yáng bǔ láo", "meaning": "出了问题及时补救", "story": "现在补救还来得及，亡羊补牢。"},
    {"idiom": "愚公移山", "pinyin": "yú gōng yí shān", "meaning": "坚持不懈，终能成功", "story": "只要有愚公移山的精神，就能成功。"},
    {"idiom": "夸父逐日", "pinyin": "kuā fù zhú rì", "meaning": "比喻有宏大的志向", "story": "我们要有夸父逐日的勇气。"},
    {"idiom": "精卫填海", "pinyin": "jīng wèi tián hǎi", "meaning": "坚持不懈的精神", "story": "精卫填海的精神值得我们学习。"}
]

levels = [
    {"id": 1, "name": "初识汉字", "description": "学习最基础的汉字", "char_indices": [0, 1, 2, 3, 4, 5], "required_score": 0},
    {"id": 2, "name": "自然万物", "description": "认识大自然中的事物", "char_indices": [6, 7, 8, 9, 10, 11], "required_score": 50},
    {"id": 3, "name": "植物王国", "description": "了解花草树木", "char_indices": [12, 13, 14, 15, 16], "required_score": 120},
    {"id": 4, "name": "动物乐园", "description": "认识可爱的动物", "char_indices": [17, 18, 19, 20, 21, 22, 23], "required_score": 200},
    {"id": 5, "name": "身体部位", "description": "了解我们的身体", "char_indices": [24, 25, 26, 27, 28, 29, 30], "required_score": 300},
    {"id": 6, "name": "数字世界", "description": "学习数字", "char_indices": [31, 32, 33, 34, 35, 36, 37, 38, 39, 40], "required_score": 420},
    {"id": 7, "name": "方向方位", "description": "认识方向和位置", "char_indices": [41, 42, 43, 44, 45, 46, 47, 48, 49], "required_score": 550},
    {"id": 8, "name": "人称代词", "description": "学习人称", "char_indices": [50, 51, 52, 53, 54, 55, 56, 57], "required_score": 700},
    {"id": 9, "name": "动作表情", "description": "认识动作和情感", "char_indices": [58, 59, 60, 61, 62, 63, 64, 65, 66], "required_score": 870},
    {"id": 10, "name": "食物颜色", "description": "认识食物和颜色", "char_indices": [67, 68, 69, 70, 71, 72, 73, 74, 75], "required_score": 1050},
    {"id": 11, "name": "学习生活", "description": "学习和生活相关的字", "char_indices": [76, 77, 78], "required_score": 1250}
]

achievements = [
    {"id": 1, "name": "识字新手", "description": "认识第一个汉字", "icon": "🌟", "condition": "learn_count >= 1"},
    {"id": 2, "name": "小小书童", "description": "认识10个汉字", "icon": "📚", "condition": "learn_count >= 10"},
    {"id": 3, "name": "汉字小达人", "description": "认识50个汉字", "icon": "🏆", "condition": "learn_count >= 50"},
    {"id": 4, "name": "识字冠军", "description": "认识所有汉字", "icon": "👑", "condition": "learn_count >= 81"},
    {"id": 5, "name": "学习之星", "description": "连续学习7天", "icon": "⭐", "condition": "streak_days >= 7"},
    {"id": 6, "name": "坚持不懈", "description": "连续学习30天", "icon": "🔥", "condition": "streak_days >= 30"},
    {"id": 7, "name": "故事大王", "description": "读完5个故事", "icon": "📖", "condition": "stories_read >= 5"},
    {"id": 8, "name": "阅读小能手", "description": "读完所有故事", "icon": "📚", "condition": "stories_read >= 12"},
    {"id": 9, "name": "拼音高手", "description": "拼音测验得满分", "icon": "🎯", "condition": "perfect_pinyin_test >= 1"},
    {"id": 10, "name": "组词小天才", "description": "成功组词100次", "icon": "✨", "condition": "word_matches >= 100"},
    {"id": 11, "name": "闯关勇士", "description": "通过第一关", "icon": "⚔️", "condition": "level_passed >= 1"},
    {"id": 12, "name": "关卡霸主", "description": "通过所有关卡", "icon": "👑", "condition": "level_passed >= 11"},
    {"id": 13, "name": "复习达人", "description": "完成100次复习", "icon": "🔄", "condition": "review_count >= 100"},
    {"id": 14, "name": "学习标兵", "description": "获得1000颗星星", "icon": "⭐", "condition": "stars >= 1000"},
    {"id": 15, "name": "全能学霸", "description": "获得所有成就", "icon": "🏅", "condition": "achievements_unlocked >= 14"}
]

data = {
    "version": "3.0",
    "total_chars": len(characters),
    "total_stories": len(stories),
    "total_reading": len(reading),
    "total_radicals": len(radicals),
    "total_idioms": len(idioms),
    "characters": characters,
    "stories": stories,
    "reading": reading,
    "radicals": radicals,
    "idioms": idioms,
    "levels": levels,
    "achievements": achievements
}

with open('/workspace/static/data.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print(f"Data generated successfully!")
print(f"Characters: {len(characters)}")
print(f"Stories: {len(stories)}")
print(f"Reading: {len(reading)}")
print(f"Radicals: {len(radicals)}")
print(f"Idioms: {len(idioms)}")
print(f"Levels: {len(levels)}")
print(f"Achievements: {len(achievements)}")