#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
汉字乐园数据生成器 v3.0
生成完整的学习数据：汉字、故事、绘本、成语、偏旁、成就
"""

import json
import os

CHARACTERS = [
    # 自然类
    {"char": "日", "pinyin": "rì", "english": "Sun", "category": "自然", "emoji": "☀️", "radical": "日", "strokes": 4,
     "stroke_order": ["竖", "横折", "横", "横"],
     "origin": {"oracle": "⊙", "seal": "日", "meaning": "古人画一个圆圈加点表示太阳"},
     "story_cn": "太阳公公每天早早起床，照亮大地。圆圆的太阳像大火球，带来温暖和光明。",
     "story_en": "Grandpa Sun wakes early each day, lighting up the earth. The round sun is like a big fireball bringing warmth and light.",
     "words": ["日出 rì chū · Sunrise", "生日 shēng rì · Birthday", "日记 rì jì · Diary", "阳光 yáng guāng · Sunshine"]},
    
    {"char": "月", "pinyin": "yuè", "english": "Moon", "category": "自然", "emoji": "🌙", "radical": "月", "strokes": 4,
     "stroke_order": ["撇", "横折钩", "横", "横"],
     "origin": {"oracle": "☽", "seal": "月", "meaning": "古人画弯弯的形状表示月亮"},
     "story_cn": "夜晚，弯弯的月亮挂在天空像一艘小船，小星星们围着月亮姐姐眨眼睛。",
     "story_en": "At night the crescent moon hangs like a small boat. Little stars twinkle around Sister Moon.",
     "words": ["月亮 yuè liàng · Moon", "月饼 yuè bǐng · Mooncake", "一月 yī yuè · January", "岁月 suì yuè · Years"]},
    
    {"char": "山", "pinyin": "shān", "english": "Mountain", "category": "自然", "emoji": "⛰️", "radical": "山", "strokes": 3,
     "stroke_order": ["竖", "竖折", "竖"],
     "origin": {"oracle": "⛰", "seal": "山", "meaning": "古人画三个山峰表示山"},
     "story_cn": "高高的山峰直插云霄，小松鼠住在山上，每天在树林里跳来跳去。",
     "story_en": "Tall peaks reach into the clouds. A little squirrel lives on the mountain, jumping among trees.",
     "words": ["火山 huǒ shān · Volcano", "爬山 pá shān · Climbing", "山水 shān shuǐ · Landscape", "高山 gāo shān · High mountain"]},
    
    {"char": "水", "pinyin": "shuǐ", "english": "Water", "category": "自然", "emoji": "💧", "radical": "水", "strokes": 4,
     "stroke_order": ["竖钩", "横撇", "撇", "捺"],
     "origin": {"oracle": "〰", "seal": "水", "meaning": "古人画流动的波浪表示水"},
     "story_cn": "哗啦啦小溪在唱歌，水滴从高处落下溅起美丽水花，小鱼在水里游来游去。",
     "story_en": "Splash splash the stream sings, water drops fall high making splashes, little fish swims happily.",
     "words": ["水果 shuǐ guǒ · Fruit", "喝水 hē shuǐ · Drink water", "河水 hé shuǐ · River water", "雨水 yǔ shuǐ · Rainwater"]},
    
    {"char": "火", "pinyin": "huǒ", "english": "Fire", "category": "自然", "emoji": "🔥", "radical": "火", "strokes": 4,
     "stroke_order": ["点", "撇", "撇", "捺"],
     "origin": {"oracle": "🔥", "seal": "火", "meaning": "古人画火焰形状表示火"},
     "story_cn": "篝火晚会开始了！火焰跳动像在跳舞。火可以做饭取暖，但小朋友不能玩火！",
     "story_en": "Campfire party begins! Flames dance. Fire cooks and keeps warm, but kids must never play with fire!",
     "words": ["火车 huǒ chē · Train", "烟火 yān huǒ · Fireworks", "大火 dà huǒ · Big fire", "灭火 miè huǒ · Extinguish fire"]},
    
    {"char": "天", "pinyin": "tiān", "english": "Sky/Day", "category": "自然", "emoji": "🌤️", "radical": "大", "strokes": 4,
     "stroke_order": ["横", "横", "撇", "捺"],
     "origin": {"oracle": "☁", "seal": "天", "meaning": "古人画一个人头顶上的空间表示天"},
     "story_cn": "蓝蓝的天空飘着白云，小鸟在天空中自由飞翔。天空真大真美啊！",
     "story_en": "White clouds float in blue sky, birds fly freely. The sky is so big and beautiful!",
     "words": ["天空 tiān kōng · Sky", "今天 jīn tiān · Today", "天气 tiān qì · Weather", "天天 tiān tiān · Every day"]},
    
    {"char": "云", "pinyin": "yún", "english": "Cloud", "category": "自然", "emoji": "☁️", "radical": "二", "strokes": 4,
     "stroke_order": ["横", "横", "撇折", "点"],
     "origin": {"oracle": "☁", "seal": "云", "meaning": "古人画云朵形状表示云"},
     "story_cn": "白云像棉花糖飘在天上。乌云来了就要下雨，云朵变化无穷真有趣！",
     "story_en": "White clouds float like cotton candy. When dark clouds come rain follows. Clouds change endlessly!",
     "words": ["白云 bái yún · White cloud", "云彩 yún cǎi · Clouds", "乌云 wū yún · Dark cloud", "云朵 yún duǒ · Cloud"]},
    
    {"char": "雨", "pinyin": "yǔ", "english": "Rain", "category": "自然", "emoji": "🌧️", "radical": "雨", "strokes": 8,
     "stroke_order": ["横", "竖", "横折钩", "竖", "点", "点", "点", "点"],
     "origin": {"oracle": "🌧", "seal": "雨", "meaning": "古人画水滴从天上落下表示雨"},
     "story_cn": "小雨滴滴答答落下来，花儿喝足了水开得更鲜艳。下雨天可以踩水洼，好开心！",
     "story_en": "Light rain falls patter-patter. Flowers drink enough water and bloom brighter. Splashing puddles is fun!",
     "words": ["下雨 xià yǔ · Rain", "雨伞 yǔ sǎn · Umbrella", "雨水 yǔ shuǐ · Rainwater", "雨衣 yǔ yī · Raincoat"]},
    
    {"char": "风", "pinyin": "fēng", "english": "Wind", "category": "自然", "emoji": "🌬️", "radical": "风", "strokes": 4,
     "stroke_order": ["撇", "横折弯钩", "撇", "点"],
     "origin": {"oracle": "🌀", "seal": "风", "meaning": "古人画风吹动的形状表示风"},
     "story_cn": "呼呼呼，风儿吹过树叶沙沙响。春风温暖，秋风凉爽，风真神奇！",
     "story_en": "Whoo whoo, wind blows through trees making rustling sounds. Spring wind is warm, autumn wind is cool!",
     "words": ["大风 dà fēng · Big wind", "风吹 fēng chuī · Wind blows", "风车 fēng chē · Windmill", "春风 chūn fēng · Spring wind"]},
    
    {"char": "雪", "pinyin": "xuě", "english": "Snow", "category": "自然", "emoji": "❄️", "radical": "雨", "strokes": 11,
     "stroke_order": ["横", "竖", "横折钩", "竖", "点", "点", "点", "点", "横", "横", "横"],
     "origin": {"oracle": "❄", "seal": "雪", "meaning": "古人画雨变成白色颗粒表示雪"},
     "story_cn": "冬天来了，白雪飘下来，大地盖上白色棉被。小朋友堆雪人打雪仗，好开心！",
     "story_en": "Winter arrives, snowflakes fall, earth covers with white quilt. Kids build snowmen and snowball fights!",
     "words": ["下雪 xià xuě · Snowing", "雪花 xuě huā · Snowflake", "雪人 xuě rén · Snowman", "白雪 bái xuě · White snow"]},
    
    # 植物类
    {"char": "花", "pinyin": "huā", "english": "Flower", "category": "植物", "emoji": "🌸", "radical": "草", "strokes": 7,
     "stroke_order": ["横", "竖", "竖", "撇", "竖弯钩", "撇", "竖弯钩"],
     "origin": {"oracle": "🌸", "seal": "花", "meaning": "古人画花草形状表示花"},
     "story_cn": "春天来了，花儿开了！红的、黄的、紫的，五颜六色的花儿真美丽！",
     "story_en": "Spring comes, flowers bloom! Red, yellow, purple - colorful flowers are so beautiful!",
     "words": ["花朵 huā duǒ · Flower", "鲜花 xiān huā · Fresh flower", "花园 huā yuán · Garden", "开花 kāi huā · Bloom"]},
    
    {"char": "草", "pinyin": "cǎo", "english": "Grass", "category": "植物", "emoji": "🌿", "radical": "草", "strokes": 9,
     "stroke_order": ["横", "竖", "竖", "竖", "横折", "横", "横", "竖", "撇"],
     "origin": {"oracle": "🌿", "seal": "草", "meaning": "古人画小草形状表示草"},
     "story_cn": "绿绿的小草长在地上，小羊喜欢吃草。草地上可以踢球玩耍！",
     "story_en": "Green grass grows on the ground, little sheep like to eat grass. We can play ball on the grass!",
     "words": ["草地 cǎo dì · Grassland", "小草 xiǎo cǎo · Little grass", "青草 qīng cǎo · Green grass", "草坪 cǎo píng · Lawn"]},
    
    {"char": "树", "pinyin": "shù", "english": "Tree", "category": "植物", "emoji": "🌳", "radical": "木", "strokes": 9,
     "stroke_order": ["横", "竖", "撇", "点", "横", "竖", "撇", "捺", "点"],
     "origin": {"oracle": "🌳", "seal": "树", "meaning": "古人画树木形状表示树"},
     "story_cn": "大树高高，树叶茂密。小鸟在树上筑巢，小朋友在树下乘凉。",
     "story_en": "Big trees are tall with dense leaves. Birds build nests in trees, children rest under them.",
     "words": ["大树 dà shù · Big tree", "树木 shù mù · Trees", "树林 shù lín · Forest", "树叶 shù yè · Leaf"]},
    
    {"char": "木", "pinyin": "mù", "english": "Wood", "category": "植物", "emoji": "🪵", "radical": "木", "strokes": 4,
     "stroke_order": ["横", "竖", "撇", "捺"],
     "origin": {"oracle": "🪵", "seal": "木", "meaning": "古人画树干和树枝表示木"},
     "story_cn": "木头可以做成桌椅、房子。木是树的一部分，很有用！",
     "story_en": "Wood can be made into tables, chairs, and houses. Wood is part of trees, very useful!",
     "words": ["木头 mù tou · Wood", "木材 mù cái · Timber", "木椅 mù yǐ · Wooden chair", "木门 mù mén · Wooden door"]},
    
    {"char": "林", "pinyin": "lín", "english": "Forest", "category": "植物", "emoji": "🌲", "radical": "木", "strokes": 8,
     "stroke_order": ["横", "竖", "撇", "捺", "横", "竖", "撇", "捺"],
     "origin": {"oracle": "🌲", "seal": "林", "meaning": "两个木在一起表示很多树"},
     "story_cn": "森林里有很多树，小动物们住在里面。树林里空气清新，真舒服！",
     "story_en": "The forest has many trees, little animals live inside. The air in the forest is fresh and comfortable!",
     "words": ["森林 sēn lín · Forest", "树林 shù lín · Woods", "林间 lín jiān · Among trees", "林子 lín zi · Woods"]},
    
    {"char": "叶", "pinyin": "yè", "english": "Leaf", "category": "植物", "emoji": "🍃", "radical": "口", "strokes": 5,
     "stroke_order": ["竖", "横折", "横", "横", "竖"],
     "origin": {"oracle": "🍃", "seal": "叶", "meaning": "古人画树枝上的叶片表示叶"},
     "story_cn": "树叶绿绿的，秋天变黄飘落。叶子可以给小虫子当家。",
     "story_en": "Leaves are green, turning yellow and falling in autumn. Leaves can be homes for little bugs.",
     "words": ["树叶 shù yè · Tree leaf", "叶子 yè zi · Leaf", "绿叶 lǜ yè · Green leaf", "落叶 luò yè · Fallen leaf"]},
    
    {"char": "果", "pinyin": "guǒ", "english": "Fruit", "category": "植物", "emoji": "🍎", "radical": "木", "strokes": 8,
     "stroke_order": ["竖", "横折", "横", "横", "横", "竖", "撇", "捺"],
     "origin": {"oracle": "🍎", "seal": "果", "meaning": "古人画树上的果实表示果"},
     "story_cn": "苹果、香蕉、橘子都是水果。水果甜甜的，小朋友都爱吃！",
     "story_en": "Apples, bananas, oranges are all fruits. Fruits are sweet, children love to eat them!",
     "words": ["水果 shuǐ guǒ · Fruit", "苹果 píng guǒ · Apple", "果实 guǒ shí · Fruit", "果树 guǒ shù · Fruit tree"]},
    
    # 动物类
    {"char": "鸟", "pinyin": "niǎo", "english": "Bird", "category": "动物", "emoji": "🐦", "radical": "鸟", "strokes": 5,
     "stroke_order": ["撇", "横折钩", "点", "竖折折钩", "横"],
     "origin": {"oracle": "🐦", "seal": "鸟", "meaning": "古人画鸟的形状表示鸟"},
     "story_cn": "小鸟在天空中飞翔，唱着美妙的歌。鸟妈妈照顾小鸟宝宝，真温馨！",
     "story_en": "Little birds fly in the sky, singing beautiful songs. Bird mom takes care of baby birds, so warm!",
     "words": ["小鸟 xiǎo niǎo · Little bird", "鸟儿 niǎo ér · Bird", "鸟巢 niǎo cháo · Nest", "飞鸟 fēi niǎo · Flying bird"]},
    
    {"char": "鱼", "pinyin": "yú", "english": "Fish", "category": "动物", "emoji": "🐟", "radical": "鱼", "strokes": 8,
     "stroke_order": ["撇", "横撇", "竖", "横折", "横", "竖", "横", "横"],
     "origin": {"oracle": "🐟", "seal": "鱼", "meaning": "古人画鱼的形状表示鱼"},
     "story_cn": "小鱼在水里游来游去，鱼鳞闪闪发光。钓鱼是很有趣的活动！",
     "story_en": "Little fish swim in water, scales shining. Fishing is a fun activity!",
     "words": ["小鱼 xiǎo yú · Little fish", "鱼儿 yú ér · Fish", "钓鱼 diào yú · Fishing", "金鱼 jīn yú · Goldfish"]},
    
    {"char": "马", "pinyin": "mǎ", "english": "Horse", "category": "动物", "emoji": "🐴", "radical": "马", "strokes": 3,
     "stroke_order": ["横折", "竖折折钩", "横"],
     "origin": {"oracle": "🐴", "seal": "马", "meaning": "古人画马的形状表示马"},
     "story_cn": "马儿跑得很快，可以帮人运输东西。骑马是一项有趣的运动！",
     "story_en": "Horses run fast, helping people transport things. Horse riding is a fun sport!",
     "words": ["小马 xiǎo mǎ · Little horse", "骑马 qí mǎ · Ride horse", "马车 mǎ chē · Horse cart", "马儿 mǎ ér · Horse"]},
    
    {"char": "牛", "pinyin": "niú", "english": "Cow", "category": "动物", "emoji": "🐄", "radical": "牛", "strokes": 4,
     "stroke_order": ["撇", "横", "横", "竖"],
     "origin": {"oracle": "🐄", "seal": "牛", "meaning": "古人画牛头形状表示牛"},
     "story_cn": "牛是勤劳的动物，可以帮农民耕田。牛奶很有营养！",
     "story_en": "Cows are hardworking animals, helping farmers plow fields. Milk is very nutritious!",
     "words": ["小牛 xiǎo niú · Little cow", "牛奶 niú nǎi · Milk", "黄牛 huáng niú · Yellow cow", "牛儿 niú ér · Cow"]},
    
    {"char": "羊", "pinyin": "yáng", "english": "Sheep", "category": "动物", "emoji": "🐑", "radical": "羊", "strokes": 6,
     "stroke_order": ["撇", "横", "横", "横", "竖", "竖"],
     "origin": {"oracle": "🐑", "seal": "羊", "meaning": "古人画羊头形状表示羊"},
     "story_cn": "小羊喜欢吃草，羊毛可以做衣服。羊儿温顺可爱！",
     "story_en": "Little sheep like eating grass, wool can make clothes. Sheep are gentle and cute!",
     "words": ["小羊 xiǎo yáng · Little sheep", "山羊 shān yáng · Goat", "羊毛 yáng máo · Wool", "羊儿 yáng ér · Sheep"]},
    
    {"char": "狗", "pinyin": "gǒu", "english": "Dog", "category": "动物", "emoji": "🐕", "radical": "犭", "strokes": 8,
     "stroke_order": ["撇", "横弯钩", "撇", "横", "竖", "横折", "横", "横"],
     "origin": {"oracle": "🐕", "seal": "狗", "meaning": "古人画狗的形状表示狗"},
     "story_cn": "小狗是人类的好朋友，会看家、会玩耍。狗狗忠诚可爱！",
     "story_en": "Dogs are human's good friends, guarding homes and playing. Dogs are loyal and cute!",
     "words": ["小狗 xiǎo gǒu · Little dog", "狗狗 gǒu gǒu · Doggy", "宠物狗 chǒng wù gǒu · Pet dog", "狗儿 gǒu ér · Dog"]},
    
    {"char": "猫", "pinyin": "māo", "english": "Cat", "category": "动物", "emoji": "🐱", "radical": "犭", "strokes": 11,
     "stroke_order": ["撇", "横弯钩", "撇", "横", "竖", "竖", "横折", "横", "竖", "横", "横"],
     "origin": {"oracle": "🐱", "seal": "猫", "meaning": "古人画猫的形状表示猫"},
     "story_cn": "小猫咪喵喵叫，喜欢抓老鼠。猫咪软软的，抱起来很舒服！",
     "story_en": "Little cats meow, like catching mice. Cats are soft, holding them is comfortable!",
     "words": ["小猫 xiǎo māo · Little cat", "猫咪 māo mī · Kitty", "宠物猫 chǒng wù māo · Pet cat", "猫儿 māo ér · Cat"]},
    
    {"char": "虫", "pinyin": "chóng", "english": "Insect", "category": "动物", "emoji": "🐛", "radical": "虫", "strokes": 6,
     "stroke_order": ["竖", "横折", "横", "竖", "横", "点"],
     "origin": {"oracle": "🐛", "seal": "虫", "meaning": "古人画虫子形状表示虫"},
     "story_cn": "小虫子在草丛里爬，蝴蝶是美丽的虫子。虫子世界很奇妙！",
     "story_en": "Little bugs crawl in grass, butterflies are beautiful insects. The insect world is amazing!",
     "words": ["小虫 xiǎo chóng · Little bug", "昆虫 kūn chóng · Insect", "虫子 chóng zi · Bug", "蝴蝶 hú dié · Butterfly"]},
    
    # 身体类
    {"char": "人", "pinyin": "rén", "english": "Person", "category": "身体", "emoji": "🧍", "radical": "人", "strokes": 2,
     "stroke_order": ["撇", "捺"],
     "origin": {"oracle": "🧍", "seal": "人", "meaning": "古人画站立的人形表示人"},
     "story_cn": "人是世界上最聪明的动物，会说话、会思考、会创造。",
     "story_en": "Humans are the smartest animals, can speak, think, and create.",
     "words": ["人们 rén men · People", "人类 rén lèi · Human", "好人 hǎo rén · Good person", "大人 dà rén · Adult"]},
    
    {"char": "手", "pinyin": "shǒu", "english": "Hand", "category": "身体", "emoji": "✋", "radical": "手", "strokes": 4,
     "stroke_order": ["撇", "横", "横", "竖钩"],
     "origin": {"oracle": "✋", "seal": "手", "meaning": "古人画手掌形状表示手"},
     "story_cn": "手可以做很多事情：写字、画画、吃饭、玩耍。保护小手很重要！",
     "story_en": "Hands can do many things: write, draw, eat, play. Protecting little hands is important!",
     "words": ["小手 xiǎo shǒu · Little hand", "双手 shuāng shǒu · Two hands", "手指 shǒu zhǐ · Finger", "握手 wò shǒu · Shake hands"]},
    
    {"char": "口", "pinyin": "kǒu", "english": "Mouth", "category": "身体", "emoji": "👄", "radical": "口", "strokes": 3,
     "stroke_order": ["竖", "横折", "横"],
     "origin": {"oracle": "👄", "seal": "口", "meaning": "古人画嘴巴形状表示口"},
     "story_cn": "嘴巴可以吃饭、说话、唱歌。微笑是最美的表情！",
     "story_en": "Mouth can eat, speak, sing. Smile is the most beautiful expression!",
     "words": ["嘴巴 zuǐ ba · Mouth", "开口 kāi kǒu · Open mouth", "人口 rén kǒu · Population", "口水 kǒu shuǐ · Saliva"]},
    
    {"char": "目", "pinyin": "mù", "english": "Eye", "category": "身体", "emoji": "👁️", "radical": "目", "strokes": 5,
     "stroke_order": ["竖", "横折", "横", "横", "横"],
     "origin": {"oracle": "👁", "seal": "目", "meaning": "古人画眼睛形状表示目"},
     "story_cn": "眼睛可以看世界，看书、看电视、看风景。保护眼睛很重要！",
     "story_en": "Eyes can see the world, read books, watch TV, see scenery. Protecting eyes is important!",
     "words": ["眼睛 yǎn jīng · Eye", "目光 mù guāng · Gaze", "目标 mù biāo · Target", "目前 mù qián · Currently"]},
    
    {"char": "耳", "pinyin": "ěr", "english": "Ear", "category": "身体", "emoji": "👂", "radical": "耳", "strokes": 6,
     "stroke_order": ["横", "竖", "竖", "横", "横", "横"],
     "origin": {"oracle": "👂", "seal": "耳", "meaning": "古人画耳朵形状表示耳"},
     "story_cn": "耳朵可以听声音，听音乐、听故事。耳朵是很重要的器官！",
     "story_en": "Ears can hear sounds, listen to music, hear stories. Ears are important organs!",
     "words": ["耳朵 ěr duo · Ear", "耳目 ěr mù · Eyes and ears", "耳机 ěr jī · Headphones", "耳语 ěr yǔ · Whisper"]},
    
    {"char": "心", "pinyin": "xīn", "english": "Heart", "category": "身体", "emoji": "💗", "radical": "心", "strokes": 4,
     "stroke_order": ["点", "卧钩", "点", "点"],
     "origin": {"oracle": "💗", "seal": "心", "meaning": "古人画心脏形状表示心"},
     "story_cn": "心脏跳动让血液流动。心也代表感情，开心、伤心都是心的感受。",
     "story_en": "Heart beats to keep blood flowing. Heart also represents feelings - happy, sad are all heart's feelings.",
     "words": ["心脏 xīn zàng · Heart", "开心 kāi xīn · Happy", "心情 xīn qíng · Mood", "心里 xīn lǐ · In heart"]},
    
    {"char": "足", "pinyin": "zú", "english": "Foot", "category": "身体", "emoji": "🦶", "radical": "足", "strokes": 7,
     "stroke_order": ["竖", "横折", "横", "竖", "横", "撇", "捺"],
     "origin": {"oracle": "🦶", "seal": "足", "meaning": "古人画脚形状表示足"},
     "story_cn": "脚可以走路、跑步、跳绳。保护小脚，穿合适的鞋子！",
     "story_en": "Feet can walk, run, jump rope. Protect little feet, wear proper shoes!",
     "words": ["脚步 jiǎo bù · Footstep", "足球 zú qiú · Soccer", "足够 zú gòu · Enough", "足迹 zú jì · Footprint"]},
    
    {"char": "头", "pinyin": "tóu", "english": "Head", "category": "身体", "emoji": "🧠", "radical": "大", "strokes": 5,
     "stroke_order": ["点", "点", "横", "撇", "点"],
     "origin": {"oracle": "🧠", "seal": "头", "meaning": "古人画人头形状表示头"},
     "story_cn": "头里有大脑，思考问题。头上有眼睛、耳朵、嘴巴、鼻子。",
     "story_en": "Head has brain for thinking. Head has eyes, ears, mouth, nose.",
     "words": ["头脑 tóu nǎo · Brain", "头发 tóu fa · Hair", "开头 kāi tóu · Beginning", "点头 diǎn tóu · Nod"]},
    
    # 数字类
    {"char": "一", "pinyin": "yī", "english": "One", "category": "数字", "emoji": "1️⃣", "radical": "一", "strokes": 1,
     "stroke_order": ["横"],
     "origin": {"oracle": "一", "seal": "一", "meaning": "古人画一横表示数字一"},
     "story_cn": "一是最小的数字，一棵树、一只鸟、一朵花。",
     "story_en": "One is the smallest number - one tree, one bird, one flower.",
     "words": ["一个 yī gè · One", "第一 dì yī · First", "一起 yī qǐ · Together", "一样 yī yàng · Same"]},
    
    {"char": "二", "pinyin": "èr", "english": "Two", "category": "数字", "emoji": "2️⃣", "radical": "二", "strokes": 2,
     "stroke_order": ["横", "横"],
     "origin": {"oracle": "二", "seal": "二", "meaning": "古人画两横表示数字二"},
     "story_cn": "二是两个东西，两只小鸟、两个苹果。",
     "story_en": "Two means two things - two birds, two apples.",
     "words": ["两个 liǎng gè · Two", "第二 dì èr · Second", "二月 èr yuè · February", "二胡 èr hú · Erhu"]},
    
    {"char": "三", "pinyin": "sān", "english": "Three", "category": "数字", "emoji": "3️⃣", "radical": "一", "strokes": 3,
     "stroke_order": ["横", "横", "横"],
     "origin": {"oracle": "三", "seal": "三", "meaning": "古人画三横表示数字三"},
     "story_cn": "三是三个东西，三只小猪、三朵花。",
     "story_en": "Three means three things - three little pigs, three flowers.",
     "words": ["三个 sān gè · Three", "第三 dì sān · Third", "三月 sān yuè · March", "三心二意 sān xīn èr yì · Half-hearted"]},
    
    {"char": "四", "pinyin": "sì", "english": "Four", "category": "数字", "emoji": "4️⃣", "radical": "囗", "strokes": 5,
     "stroke_order": ["竖", "横折", "撇", "竖弯", "横"],
     "origin": {"oracle": "四", "seal": "四", "meaning": "古人画四条线或方框表示数字四"},
     "story_cn": "四是四个东西，四季、四方。",
     "story_en": "Four means four things - four seasons, four directions.",
     "words": ["四个 sì gè · Four", "第四 dì sì · Fourth", "四季 sì jì · Four seasons", "四周 sì zhōu · Surroundings"]},
    
    {"char": "五", "pinyin": "wǔ", "english": "Five", "category": "数字", "emoji": "5️⃣", "radical": "二", "strokes": 4,
     "stroke_order": ["横", "竖", "横折", "横"],
     "origin": {"oracle": "五", "seal": "五", "meaning": "古人画交叉形状表示数字五"},
     "story_cn": "五是五个东西，五根手指、五颜六色。",
     "story_en": "Five means five things - five fingers, colorful.",
     "words": ["五个 wǔ gè · Five", "第五 dì wǔ · Fifth", "五月 wǔ yuè · May", "五彩 wǔ cǎi · Five colors"]},
    
    {"char": "六", "pinyin": "liù", "english": "Six", "category": "数字", "emoji": "6️⃣", "radical": "八", "strokes": 4,
     "stroke_order": ["点", "横", "撇", "点"],
     "origin": {"oracle": "六", "seal": "六", "meaning": "古人画房屋形状表示数字六"},
     "story_cn": "六是六个东西，六边形。",
     "story_en": "Six means six things - hexagon.",
     "words": ["六个 liù gè · Six", "第六 dì liù · Sixth", "六月 liù yuè · June", "六一 liù yī · June 1st"]},
    
    {"char": "七", "pinyin": "qī", "english": "Seven", "category": "数字", "emoji": "7️⃣", "radical": "一", "strokes": 2,
     "stroke_order": ["横", "竖弯钩"],
     "origin": {"oracle": "七", "seal": "七", "meaning": "古人画十字加弯曲表示数字七"},
     "story_cn": "七是七个东西，七彩虹。",
     "story_en": "Seven means seven things - rainbow has seven colors.",
     "words": ["七个 qī gè · Seven", "第七 dì qī · Seventh", "七月 qī yuè · July", "七彩 qī cǎi · Seven colors"]},
    
    {"char": "八", "pinyin": "bā", "english": "Eight", "category": "数字", "emoji": "8️⃣", "radical": "八", "strokes": 2,
     "stroke_order": ["撇", "捺"],
     "origin": {"oracle": "八", "seal": "八", "meaning": "古人画分开的两笔表示数字八"},
     "story_cn": "八是八个东西，八仙过海。",
     "story_en": "Eight means eight things - eight immortals cross the sea.",
     "words": ["八个 bā gè · Eight", "第八 dì bā · Eighth", "八月 bā yuè · August", "八方 bā fāng · Eight directions"]},
    
    {"char": "九", "pinyin": "jiǔ", "english": "Nine", "category": "数字", "emoji": "9️⃣", "radical": "丿", "strokes": 2,
     "stroke_order": ["撇", "横折弯钩"],
     "origin": {"oracle": "九", "seal": "九", "meaning": "古人画弯曲形状表示数字九"},
     "story_cn": "九是九个东西，九九重阳。",
     "story_en": "Nine means nine things - Double Ninth Festival.",
     "words": ["九个 jiǔ gè · Nine", "第九 dì jiǔ · Ninth", "九月 jiǔ yuè · September", "九九 jiǔ jiǔ · Nine nine"]},
    
    {"char": "十", "pinyin": "shí", "english": "Ten", "category": "数字", "emoji": "🔟", "radical": "十", "strokes": 2,
     "stroke_order": ["横", "竖"],
     "origin": {"oracle": "十", "seal": "十", "meaning": "古人画十字表示数字十"},
     "story_cn": "十是十个东西，十全十美。",
     "story_en": "Ten means ten things - perfect.",
     "words": ["十个 shí gè · Ten", "第十 dì shí · Tenth", "十月 shí yuè · October", "十分 shí fēn · Very"]},
    
    # 方位类
    {"char": "上", "pinyin": "shàng", "english": "Up/Above", "category": "方位", "emoji": "⬆️", "radical": "一", "strokes": 3,
     "stroke_order": ["竖", "横", "横"],
     "origin": {"oracle": "上", "seal": "上", "meaning": "古人画指示符号表示上方"},
     "story_cn": "小鸟飞上天空，气球飘上高空。上就是高高的方向。",
     "story_en": "Birds fly up to sky, balloons float up high. Up means the high direction.",
     "words": ["上面 shàng miàn · Above", "向上 xiàng shàng · Upward", "上山 shàng shān · Go up mountain", "上课 shàng kè · Attend class"]},
    
    {"char": "下", "pinyin": "xià", "english": "Down/Below", "category": "方位", "emoji": "⬇️", "radical": "一", "strokes": 3,
     "stroke_order": ["横", "竖", "点"],
     "origin": {"oracle": "下", "seal": "下", "meaning": "古人画指示符号表示下方"},
     "story_cn": "小虫爬下地面，雨滴落下天空。下就是低低的方向。",
     "story_en": "Bugs crawl down to ground, raindrops fall down from sky. Down means the low direction.",
     "words": ["下面 xià miàn · Below", "向下 xiàng xià · Downward", "下山 xià shān · Go down mountain", "下课 xià kè · Class ends"]},
    
    {"char": "左", "pinyin": "zuǒ", "english": "Left", "category": "方位", "emoji": "⬅️", "radical": "工", "strokes": 5,
     "stroke_order": ["横", "撇", "横", "竖", "横"],
     "origin": {"oracle": "左", "seal": "左", "meaning": "古人画左手形状表示左"},
     "story_cn": "左手拿东西，左脚走路。左就是身体的一边。",
     "story_en": "Left hand holds things, left foot walks. Left is one side of the body.",
     "words": ["左边 zuǒ biān · Left side", "左手 zuǒ shǒu · Left hand", "向左 xiàng zuǒ · To left", "左右 zuǒ yòu · Left and right"]},
    
    {"char": "右", "pinyin": "yòu", "english": "Right", "category": "方位", "emoji": "➡️", "radical": "口", "strokes": 5,
     "stroke_order": ["横", "撇", "横", "竖", "横"],
     "origin": {"oracle": "右", "seal": "右", "meaning": "古人画右手形状表示右"},
     "story_cn": "右手写字，右脚踢球。右就是身体的另一边。",
     "story_en": "Right hand writes, right foot kicks ball. Right is the other side of the body.",
     "words": ["右边 yòu biān · Right side", "右手 yòu shǒu · Right hand", "向右 xiàng yòu · To right", "左右 zuǒ yòu · Left and right"]},
    
    {"char": "中", "pinyin": "zhōng", "english": "Middle/Center", "category": "方位", "emoji": "⏺️", "radical": "丨", "strokes": 4,
     "stroke_order": ["竖", "横折", "横", "竖"],
     "origin": {"oracle": "中", "seal": "中", "meaning": "古人画旗帜在中间表示中"},
     "story_cn": "中间是最中心的位置。中国是我们的国家。",
     "story_en": "Middle is the center position. China is our country.",
     "words": ["中间 zhōng jiān · Middle", "中国 zhōng guó · China", "中心 zhōng xīn · Center", "中午 zhōng wǔ · Noon"]},
    
    {"char": "东", "pinyin": "dōng", "english": "East", "category": "方位", "emoji": "🌅", "radical": "一", "strokes": 5,
     "stroke_order": ["横", "撇", "竖钩", "撇", "点"],
     "origin": {"oracle": "东", "seal": "东", "meaning": "古人画太阳升起的方向表示东"},
     "story_cn": "太阳从东方升起，东方是太阳出来的方向。",
     "story_en": "Sun rises from the east, east is where the sun comes out.",
     "words": ["东方 dōng fāng · East", "东边 dōng biān · East side", "东风 dōng fēng · East wind", "东西 dōng xi · Things"]},
    
    {"char": "西", "pinyin": "xī", "english": "West", "category": "方位", "emoji": "🌇", "radical": "西", "strokes": 6,
     "stroke_order": ["横", "竖", "横折", "撇", "点", "撇"],
     "origin": {"oracle": "西", "seal": "西", "meaning": "古人画太阳落下的方向表示西"},
     "story_cn": "太阳从西方落下，西方是太阳消失的方向。",
     "story_en": "Sun sets in the west, west is where the sun disappears.",
     "words": ["西方 xī fāng · West", "西边 xī biān · West side", "西风 xī fēng · West wind", "东西 dōng xi · Things"]},
    
    {"char": "南", "pinyin": "nán", "english": "South", "category": "方位", "emoji": "🧭", "radical": "十", "strokes": 9,
     "stroke_order": ["横", "竖", "横折钩", "竖", "横", "横", "竖", "横", "横"],
     "origin": {"oracle": "南", "seal": "南", "meaning": "古人画房屋朝向表示南"},
     "story_cn": "南方天气温暖，南方有很多热带水果。",
     "story_en": "South has warm weather, south has many tropical fruits.",
     "words": ["南方 nán fāng · South", "南边 nán biān · South side", "南极 nán jí · South Pole", "南风 nán fēng · South wind"]},
    
    {"char": "北", "pinyin": "běi", "english": "North", "category": "方位", "emoji": "❄️", "radical": "北", "strokes": 5,
     "stroke_order": ["竖", "横", "提", "撇", "竖弯钩"],
     "origin": {"oracle": "北", "seal": "北", "meaning": "古人画背靠背的人表示北"},
     "story_cn": "北方天气寒冷，北方有美丽的雪景。",
     "story_en": "North has cold weather, north has beautiful snow scenery.",
     "words": ["北方 běi fāng · North", "北边 běi biān · North side", "北极 běi jí · North Pole", "北风 běi fēng · North wind"]},
    
    # 人称类
    {"char": "我", "pinyin": "wǒ", "english": "I/Me", "category": "人称", "emoji": "🙋", "radical": "戈", "strokes": 7,
     "stroke_order": ["撇", "横", "竖钩", "提", "斜钩", "撇", "点"],
     "origin": {"oracle": "我", "seal": "我", "meaning": "古人画武器形状表示我"},
     "story_cn": "我是小朋友，我爱学习，我爱玩耍。",
     "story_en": "I am a child, I love learning, I love playing.",
     "words": ["我们 wǒ men · We", "我的 wǒ de · My", "自我 zì wǒ · Self", "小我 xiǎo wǒ · Little me"]},
    
    {"char": "你", "pinyin": "nǐ", "english": "You", "category": "人称", "emoji": "👉", "radical": "人", "strokes": 7,
     "stroke_order": ["撇", "竖", "撇", "竖", "横折", "横", "横"],
     "origin": {"oracle": "你", "seal": "你", "meaning": "古人画人加指示表示你"},
     "story_cn": "你是我的好朋友，我们一起玩吧！",
     "story_en": "You are my good friend, let's play together!",
     "words": ["你们 nǐ men · You (plural)", "你的 nǐ de · Your", "你好 nǐ hǎo · Hello", "迷你 mí nǐ · Mini"]},
    
    {"char": "他", "pinyin": "tā", "english": "He/Him", "category": "人称", "emoji": "👨", "radical": "人", "strokes": 5,
     "stroke_order": ["撇", "竖", "横折钩", "竖", "竖弯钩"],
     "origin": {"oracle": "他", "seal": "他", "meaning": "古人画人加指示表示他"},
     "story_cn": "他是小明，他喜欢踢足球。",
     "story_en": "He is Xiao Ming, he likes playing soccer.",
     "words": ["他们 tā men · They", "他的 tā de · His", "他人 tā rén · Others", "其他 qí tā · Other"]},
    
    {"char": "她", "pinyin": "tā", "english": "She/Her", "category": "人称", "emoji": "👩", "radical": "女", "strokes": 6,
     "stroke_order": ["撇", "横撇", "竖", "横折钩", "竖", "竖弯钩"],
     "origin": {"oracle": "她", "seal": "她", "meaning": "古人画女加指示表示她"},
     "story_cn": "她是小红，她喜欢画画。",
     "story_en": "She is Xiao Hong, she likes drawing.",
     "words": ["她们 tā men · They (female)", "她的 tā de · Her", "她人 tā rén · She person", "其他 qí tā · Other"]},
    
    {"char": "爸", "pinyin": "bà", "english": "Father", "category": "人称", "emoji": "👨", "radical": "父", "strokes": 8,
     "stroke_order": ["撇", "点", "撇", "捺", "横折", "横", "横", "横"],
     "origin": {"oracle": "爸", "seal": "爸", "meaning": "父亲加巴音表示爸"},
     "story_cn": "爸爸爱我，爸爸工作辛苦。我爱爸爸！",
     "story_en": "Father loves me, father works hard. I love father!",
     "words": ["爸爸 bà ba · Father", "老爸 lǎo bà · Dad", "爸妈 bà mā · Parents", "父爸 fù bà · Father"]},
    
    {"char": "妈", "pinyin": "mā", "english": "Mother", "category": "人称", "emoji": "👩", "radical": "女", "strokes": 6,
     "stroke_order": ["撇", "横撇", "竖", "横折钩", "竖", "竖弯钩"],
     "origin": {"oracle": "妈", "seal": "妈", "meaning": "母亲加马音表示妈"},
     "story_cn": "妈妈爱我，妈妈照顾我。我爱妈妈！",
     "story_en": "Mother loves me, mother takes care of me. I love mother!",
     "words": ["妈妈 mā ma · Mother", "老妈 lǎo mā · Mom", "爸妈 bà mā · Parents", "妈咪 mā mī · Mommy"]},
    
    {"char": "爷", "pinyin": "yé", "english": "Grandfather", "category": "人称", "emoji": "👴", "radical": "父", "strokes": 6,
     "stroke_order": ["撇", "点", "撇", "捺", "横", "竖钩"],
     "origin": {"oracle": "爷", "seal": "爷", "meaning": "父亲加耶音表示爷"},
     "story_cn": "爷爷爱我，爷爷讲故事。我爱爷爷！",
     "story_en": "Grandpa loves me, grandpa tells stories. I love grandpa!",
     "words": ["爷爷 yé ye · Grandpa", "大爷 dà yé · Uncle", "老爷 lǎo yé · Master", "爷孙 yé sūn · Grandpa and grandchild"]},
    
    {"char": "奶", "pinyin": "nǎi", "english": "Grandmother", "category": "人称", "emoji": "👵", "radical": "女", "strokes": 5,
     "stroke_order": ["撇", "横撇", "竖", "横折钩", "横"],
     "origin": {"oracle": "奶", "seal": "奶", "meaning": "女性加乃音表示奶"},
     "story_cn": "奶奶爱我，奶奶做饭好吃。我爱奶奶！",
     "story_en": "Grandma loves me, grandma cooks delicious food. I love grandma!",
     "words": ["奶奶 nǎi nai · Grandma", "牛奶 niú nǎi · Milk", "奶粉 nǎi fěn · Milk powder", "奶奶家 nǎi nai jiā · Grandma's home"]},
    
    # 动作类
    {"char": "走", "pinyin": "zǒu", "english": "Walk/Go", "category": "动作", "emoji": "🚶", "radical": "走", "strokes": 7,
     "stroke_order": ["横", "竖", "横", "竖", "横", "撇", "捺"],
     "origin": {"oracle": "走", "seal": "走", "meaning": "古人画人走路形状表示走"},
     "story_cn": "小朋友学会走路了！走路上学，走路回家。",
     "story_en": "Children learn to walk! Walk to school, walk home.",
     "words": ["走路 zǒu lù · Walk", "走开 zǒu kāi · Go away", "走出 zǒu chū · Walk out", "走进 zǒu jìn · Walk in"]},
    
    {"char": "跑", "pinyin": "pǎo", "english": "Run", "category": "动作", "emoji": "🏃", "radical": "足", "strokes": 12,
     "stroke_order": ["竖", "横折", "横", "竖", "横", "撇", "捺", "横折钩", "竖", "横折", "横", "横"],
     "origin": {"oracle": "跑", "seal": "跑", "meaning": "足加包音表示跑"},
     "story_cn": "跑步比赛真有趣！小朋友跑得很快。",
     "story_en": "Running race is fun! Children run very fast.",
     "words": ["跑步 pǎo bù · Run", "跑车 pǎo chē · Sports car", "跑开 pǎo kāi · Run away", "跑进 pǎo jìn · Run in"]},
    
    {"char": "跳", "pinyin": "tiào", "english": "Jump", "category": "动作", "emoji": "🦘", "radical": "足", "strokes": 13,
     "stroke_order": ["竖", "横折", "横", "竖", "横", "撇", "捺", "竖", "横折", "横", "竖", "横", "横"],
     "origin": {"oracle": "跳", "seal": "跳", "meaning": "足加兆音表示跳"},
     "story_cn": "跳绳、跳高、跳远都是运动。小朋友跳得高！",
     "story_en": "Jump rope, high jump, long jump are sports. Children jump high!",
     "words": ["跳绳 tiào shéng · Jump rope", "跳高 tiào gāo · High jump", "跳远 tiào yuǎn · Long jump", "跳舞 tiào wǔ · Dance"]},
    
    {"char": "吃", "pinyin": "chī", "english": "Eat", "category": "动作", "emoji": "😋", "radical": "口", "strokes": 6,
     "stroke_order": ["竖", "横折", "横", "撇", "横", "横折弯钩"],
     "origin": {"oracle": "吃", "seal": "吃", "meaning": "口加乞音表示吃"},
     "story_cn": "吃饭时间到了！吃蔬菜、吃水果，健康饮食。",
     "story_en": "Time to eat! Eat vegetables, eat fruits, healthy diet.",
     "words": ["吃饭 chī fàn · Eat meal", "好吃 hǎo chī · Delicious", "吃掉 chī diào · Eat up", "吃糖 chī táng · Eat candy"]},
    
    {"char": "喝", "pinyin": "hē", "english": "Drink", "category": "动作", "emoji": "🥤", "radical": "口", "strokes": 12,
     "stroke_order": ["竖", "横折", "横", "竖", "横折", "横", "撇", "横钩", "撇", "捺", "竖", "横折"],
     "origin": {"oracle": "喝", "seal": "喝", "meaning": "口加曷音表示喝"},
     "story_cn": "喝水、喝牛奶、喝果汁。多喝水身体好！",
     "story_en": "Drink water, drink milk, drink juice. Drink more water for good health!",
     "words": ["喝水 hē shuǐ · Drink water", "喝茶 hē chá · Drink tea", "喝酒 hē jiǔ · Drink alcohol", "喝药 hē yào · Take medicine"]},
    
    {"char": "笑", "pinyin": "xiào", "english": "Smile", "category": "动作", "emoji": "😊", "radical": "竹", "strokes": 10,
     "stroke_order": ["撇", "横", "点", "撇", "横", "点", "撇", "撇", "捺", "点"],
     "origin": {"oracle": "笑", "seal": "笑", "meaning": "竹子下面有夭，表示开心"},
     "story_cn": "微笑是最美的表情。每天笑一笑，心情好！",
     "story_en": "Smile is the most beautiful expression. Smile every day, feel happy!",
     "words": ["微笑 wēi xiào · Smile", "大笑 dà xiào · Laugh loudly", "笑话 xiào hua · Joke", "笑容 xiào róng · Smile"]},
    
    {"char": "哭", "pinyin": "kū", "english": "Cry", "category": "动作", "emoji": "😢", "radical": "犬", "strokes": 10,
     "stroke_order": ["竖", "横折", "横", "竖", "横折", "横", "撇", "捺", "点", "点"],
     "origin": {"oracle": "哭", "seal": "哭", "meaning": "眼睛流泪表示哭"},
     "story_cn": "哭是表达伤心的方式。哭出来会好受一些。",
     "story_en": "Crying is a way to express sadness. It feels better after crying.",
     "words": ["哭声 kū shēng · Cry", "哭泣 kū qì · Weep", "哭脸 kū liǎn · Sad face", "哭啼 kū tí · Whimper"]},
    
    # 情感类
    {"char": "爱", "pinyin": "ài", "english": "Love", "category": "情感", "emoji": "❤️", "radical": "爫", "strokes": 10,
     "stroke_order": ["撇", "点", "点", "撇", "点", "横撇", "横", "撇", "撇", "捺"],
     "origin": {"oracle": "爱", "seal": "爱", "meaning": "心中有喜爱的人"},
     "story_cn": "爱是温暖的感觉。我爱爸爸妈妈，我爱这个世界！",
     "story_en": "Love is a warm feeling. I love my parents, I love the world!",
     "words": ["爱心 ài xīn · Love", "爱情 ài qíng · Love", "爱护 ài hù · Cherish", "可爱 kě ài · Cute"]},
    
    {"char": "喜", "pinyin": "xǐ", "english": "Happy", "category": "情感", "emoji": "😄", "radical": "士", "strokes": 12,
     "stroke_order": ["横", "竖", "横折", "横", "点", "撇", "横", "竖", "横折", "横", "竖钩", "撇", "点"],
     "origin": {"oracle": "喜", "seal": "喜", "meaning": "古人表示高兴"},
     "story_cn": "喜事就是开心的事。过年是喜事，生日也是喜事！",
     "story_en": "Happy events are joyful things. Chinese New Year is happy, birthday is happy!",
     "words": ["喜欢 xǐ huān · Like", "高兴 gāo xìng · Happy", "喜事 xǐ shì · Happy event", "喜庆 xǐ qìng · Festive"]},
    
    {"char": "乐", "pinyin": "lè", "english": "Joy", "category": "情感", "emoji": "🎊", "radical": "丿", "strokes": 5,
     "stroke_order": ["撇", "竖折", "竖钩", "撇", "点"],
     "origin": {"oracle": "乐", "seal": "乐", "meaning": "古人表示快乐"},
     "story_cn": "快乐是美好的感觉。唱歌、跳舞、玩耍都很快乐！",
     "story_en": "Joy is a wonderful feeling. Singing, dancing, playing are all joyful!",
     "words": ["快乐 kuài lè · Happy", "欢乐 huān lè · Joy", "乐园 lè yuán · Amusement park", "乐意 lè yì · Willing"]},
    
    {"char": "好", "pinyin": "hǎo", "english": "Good", "category": "情感", "emoji": "👍", "radical": "女", "strokes": 6,
     "stroke_order": ["撇", "横撇", "竖", "横折", "横", "横"],
     "origin": {"oracle": "好", "seal": "好", "meaning": "女子在一起表示美好"},
     "story_cn": "好就是很棒的意思。好人、好事、好心情！",
     "story_en": "Good means excellent. Good people, good things, good mood!",
     "words": ["好人 hǎo rén · Good person", "好事 hǎo shì · Good thing", "好看 hǎo kàn · Good looking", "好玩 hǎo wán · Fun"]},
    
    # 食物类
    {"char": "米", "pinyin": "mǐ", "english": "Rice", "category": "食物", "emoji": "🍚", "radical": "米", "strokes": 6,
     "stroke_order": ["点", "撇", "横", "竖", "撇", "捺"],
     "origin": {"oracle": "米", "seal": "米", "meaning": "古人画米粒形状表示米"},
     "story_cn": "米饭是主食。大米香喷喷，小朋友要好好吃饭！",
     "story_en": "Rice is the staple food. Rice smells good, children should eat well!",
     "words": ["米饭 mǐ fàn · Rice", "大米 dà mǐ · Rice", "小米 xiǎo mǐ · Millet", "玉米 yù mǐ · Corn"]},
    
    {"char": "面", "pinyin": "miàn", "english": "Noodle", "category": "食物", "emoji": "🍜", "radical": "面", "strokes": 9,
     "stroke_order": ["横", "竖", "横折", "横", "竖", "撇", "点", "撇", "捺"],
     "origin": {"oracle": "面", "seal": "面", "meaning": "古人画面粉形状表示面"},
     "story_cn": "面条长长的，可以做很多好吃的。牛肉面、鸡蛋面都很好吃！",
     "story_en": "Noodles are long, can make many delicious dishes. Beef noodles, egg noodles are delicious!",
     "words": ["面条 miàn tiáo · Noodles", "面包 miàn bāo · Bread", "面粉 miàn fěn · Flour", "方便面 fāng biàn miàn · Instant noodles"]},
    
    {"char": "肉", "pinyin": "ròu", "english": "Meat", "category": "食物", "emoji": "🥩", "radical": "肉", "strokes": 6,
     "stroke_order": ["竖", "横折钩", "撇", "点", "撇", "点"],
     "origin": {"oracle": "肉", "seal": "肉", "meaning": "古人画肉的形状表示肉"},
     "story_cn": "肉很有营养，能帮助小朋友长大。鸡肉、鱼肉都很好！",
     "story_en": "Meat is nutritious, helps children grow. Chicken, fish are all good!",
     "words": ["猪肉 zhū ròu · Pork", "牛肉 niú ròu · Beef", "鸡肉 jī ròu · Chicken", "鱼肉 yú ròu · Fish"]},
    
    {"char": "菜", "pinyin": "cài", "english": "Vegetable", "category": "食物", "emoji": "🥬", "radical": "艹", "strokes": 11,
     "stroke_order": ["横", "竖", "竖", "横", "撇", "竖", "横折", "竖", "撇", "捺", "点"],
     "origin": {"oracle": "菜", "seal": "菜", "meaning": "草本植物可食用表示菜"},
     "story_cn": "蔬菜很健康，有很多维生素。多吃蔬菜身体棒！",
     "story_en": "Vegetables are healthy, have many vitamins. Eat more vegetables for good health!",
     "words": ["蔬菜 shū cài · Vegetables", "白菜 bái cài · Chinese cabbage", "青菜 qīng cài · Green vegetables", "买菜 mǎi cài · Buy vegetables"]},
    
    # 颜色类
    {"char": "红", "pinyin": "hóng", "english": "Red", "category": "颜色", "emoji": "🔴", "radical": "纟", "strokes": 6,
     "stroke_order": ["撇折", "撇折", "提", "横", "竖", "横"],
     "origin": {"oracle": "红", "seal": "红", "meaning": "丝线染成红色"},
     "story_cn": "红色是喜庆的颜色。过年时红灯笼、红鞭炮，很热闹！",
     "story_en": "Red is a festive color. Red lanterns, red firecrackers during Chinese New Year!",
     "words": ["红色 hóng sè · Red", "红花 hóng huā · Red flower", "红旗 hóng qí · Red flag", "红火 hóng huǒ · Prosperous"]},
    
    {"char": "黄", "pinyin": "huáng", "english": "Yellow", "category": "颜色", "emoji": "🟡", "radical": "黄", "strokes": 11,
     "stroke_order": ["横", "竖", "竖", "横", "竖", "横折", "横", "竖", "撇", "点"],
     "origin": {"oracle": "黄", "seal": "黄", "meaning": "古人画玉佩表示黄色"},
     "story_cn": "黄色是阳光的颜色。秋天的树叶变黄了，很漂亮！",
     "story_en": "Yellow is the color of sunshine. Autumn leaves turn yellow, very beautiful!",
     "words": ["黄色 huáng sè · Yellow", "黄金 huáng jīn · Gold", "黄河 huáng hé · Yellow River", "黄昏 huáng hūn · Dusk"]},
    
    {"char": "蓝", "pinyin": "lán", "english": "Blue", "category": "颜色", "emoji": "🔵", "radical": "艹", "strokes": 13,
     "stroke_order": ["横", "竖", "竖", "竖", "竖折", "竖", "横", "竖", "横折", "横", "横", "撇", "竖"],
     "origin": {"oracle": "蓝", "seal": "蓝", "meaning": "蓝草可以染蓝色"},
     "story_cn": "蓝色是天空和大海的颜色。蓝色让人感觉很舒服！",
     "story_en": "Blue is the color of sky and sea. Blue makes people feel comfortable!",
     "words": ["蓝色 lán sè · Blue", "蓝天 lán tiān · Blue sky", "蓝色 lán sè · Blue", "蓝图 lán tú · Blueprint"]},
    
    {"char": "绿", "pinyin": "lǜ", "english": "Green", "category": "颜色", "emoji": "🟢", "radical": "纟", "strokes": 11,
     "stroke_order": ["撇折", "撇折", "提", "横折", "横", "竖钩", "点", "撇", "点"],
     "origin": {"oracle": "绿", "seal": "绿", "meaning": "丝线染成绿色"},
     "story_cn": "绿色是小草和树叶的颜色。绿色代表生命！",
     "story_en": "Green is the color of grass and leaves. Green represents life!",
     "words": ["绿色 lǜ sè · Green", "草地 cǎo dì · Grassland", "绿叶 lǜ yè · Green leaf",